### ISSUE TITLE
[bug] nil pointer when attempting to `ingestCertifyGood`

### ISSUE THREAD

**Issue by bobmcwhirter** [guacsec/guac#1007]
NPE when attempting to `ingestCertifyGood` without a pkgMatchType Spec

**To Reproduce**

While this works:
```
mutation CertifyGoodM1($package: PkgInputSpec!, $origin: String!, $collector: String!, $justification: String!) {
  ingestCertifyGood(
    subject: {
      package: $package
    }
    pkgMatchType: { pkg: SPECIFIC_VERSION }
    certifyGood: {
      justification: $justification
      origin: $origin
      collector: $collector
    }
  ) {
    ...allCertifyGoodTree
  }
}
```

The variant without specifying `pkgMatchType`

```
mutation CertifyGoodM1($package: PkgInputSpec!, $origin: String!, $collector: String!, $justification: String!) {
  ingestCertifyGood(
    subject: {
      package: $package
    }
    certifyGood: {
      justification: $justification
      origin: $origin
      collector: $collector
    }
  ) {
    ...allCertifyGoodTree
  }
}
```

causes an nil pointer.

**Expected behavior**
Either not a nil pointer, or a sensible error indicating that `pkgMatchType` is non-optional.

**Screenshots**

```
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).ingestCertifyGood(0x140002188c0, {0x103760fa0, 0x14000357bc0}, {0x140003279a0, 0x0, 0x0}, 0x0, {{0x140000262bc, 0x4}, {0x14000026170, ...}, ...}, ...)
	/Users/bob/repos/trustification/guac/pkg/assembler/backends/inmem/certifyGood.go:82 +0x67c
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).IngestCertifyGood(0x140003990b8?, {0x103760fa0?, 0x14000357bc0?}, {0x140003279a0?, 0x0?, 0x0?}, 0x1?, {{0x140000262bc, 0x4}, {0x14000026170, ...}, ...})
	/Users/bob/repos/trustification/guac/pkg/assembler/backends/inmem/certifyGood.go:62 +0x54
```

**GUAC version**

`main#HEAD` as of last week.

**Additional context**

Seems `matchFlags` is deemed optional here https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/schema/certifyGood.graphql#L76

**Comment by pxp928** [comment]
Thanks for the bug report @bobmcwhirter! `pkgMatchType` is optional when a source or artifact is specified but we do need to add a check when a package is specified, `pkgMatchType` is non-optional.

**Comment by bobmcwhirter** [comment]
I'm probably not yet fully comprehending it all, but could the `version` aspect of the `PkgInputSpec` be optional, instead of the `pkgMatchType` stuff? If `null`, then match all versions, if non-`null`, match the version as specified?  Or do other parts also figure into the matching, besides only `version`?

**Comment by pxp928** [comment]
We cannot make `version` in `PkgInputSpec` optional as it is a required component when ingesting packages. The `pkgMatchType` is used if the user wants to certify a package name (and all versions below it) or a specific version of a package. All packages will contain a version node (even if it's empty).

**Comment by mrizzi** [comment]
> We cannot make `version` in `PkgInputSpec` optional as it is a required component when ingesting packages. The `pkgMatchType` is used if the user wants to certify a package name (and all versions below it) or a specific version of a package. All packages will contain a version node (even if it's empty).

@pxp928 do you think it's worth making `pkgMatchType`  mandatory?

**Comment by pxp928** [comment]
Yup, I have a PR open that I can fix this in. It makes sense to make it mandatory to avoid confusion on the user side.
