### ISSUE TITLE
[feature] When ingesting VEX documents add NoVuln node if package is not affected

### ISSUE THREAD

**Issue by dejanb** [guacsec/guac#1015]
**Is your feature request related to a problem? Please describe.**
During development of [VEX CSAF support](https://github.com/guacsec/guac/pull/729) we ignored packages described as not affected by the vulnerability. It was left to be handled in separate issue.

**Describe the solution you'd like**
If package is not affected, add `NoVuln` node.

**Comment by lumjjb** [comment]
@dejanb I think i recall this conversation being about products that did not have a vulnerability. Is that accurate? or am i recalling wrong?
