### ISSUE TITLE
[feature] Upgrade go-vex dependency to a released version

### ISSUE THREAD

**Issue by lulf** [guacsec/guac#1017]
**Is your feature request related to a problem? Please describe.**
The initial support for ingesting CSAF uses an unreleased version of go-vex. A released version of go-vex with CSAF support should be used instead.

**Describe the solution you'd like**
Once https://github.com/openvex/go-vex/issues/44 is resolved, a PR should be made for guac to upgrade the go-vex version.

**Comment by lumjjb** [comment]
@lulf can i assign this issue to you to track when that is merged?
