### ISSUE TITLE
task: [processor/ingestor] CycloneDX support

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#102]
Add support to ingest CycloneDX documents

**Comment by cpendery** [comment]
@lumjjb Happy to contribute support for this. Can you assign me?

**Comment by lumjjb** [comment]
awesome @cpendery , i would start with the processor and guesser! https://github.com/guacsec/guac/pull/104

**Comment by lumjjb** [comment]
woop! #140 introduces json cyclone DX support, left needing a processor and i think we can close up this issue for now! @cpendery - if you add the parser portion for XML we should be good to go.

**Comment by cpendery** [comment]
@lumjjb Just finished up the PR for the XML support. Happy to contribute anything last minute as you all prep for KubeCon on Monday

**Comment by lumjjb** [comment]
Awesome. We should be good for kubecon for now! Thanks for helping out!!!
