### ISSUE TITLE
[feature] Add timestamp to verbs that don't have them

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1030]
**Is your feature request related to a problem? Please describe.**
Currently, timestamp field is only on the following "verbs":

```
CertifyScorecard
CertifyVuln
CertifyVEXStatement
HasSourceAt
HasSLSA
```

They should be added to others such as `CertifyGood`, `CertifyBad`, and `hasSBOM`.  

Use-case:
From @bobmcwhirter: For instance, if I want to see if a CertifyGood is more recent than some CertifyBad, or vice-versa.

**Describe the solution you'd like**

Determine if timestamps need to be added to the verbs that are currently missing this field (and new ones as they are introduced).

**Comment by pxp928** [comment]
Thoughts @guacsec/guac-maint?

**Comment by mihaimaruseac** [comment]
For the certify good/bad cases, I see the need for timestamps, to add an ordering of these when there are multiples referring to the same node.

I think we need one for the SBOM too, since we might have multiple SBOMs for the same node and we could see if these get more complete over time, etc.

**Comment by lumjjb** [comment]
+1 on this, i think the data model needs to be considered in this case for deduplication, but that can be hidden behind the GQL.

**Comment by nathannaveen** [comment]
Could I work on this?

**Comment by pxp928** [comment]
Reopening issue to update the other backends: Arango and Ent
