### ISSUE TITLE
[ingestion/data-quality issue] SLSA parser should ensure fields are non-null before dereferencing 

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#1059]
**Describe the bug**

Currently [SLSA parser](https://github.com/guacsec/guac/blob/main/pkg/ingestor/parser/slsa/parser_slsa.go#L199) sometimes assumes fields are non-nil and dererefences them, which when provided with a non-complete document causes a NPE.

**To Reproduce**

Make a SLSA predicate where there is no "predicate" field

**Expected behavior**
It should fail via throwing an error when information required is not present. or alter the inputs to GQL accordingly

**Screenshots**
```
{"level":"info","ts":1689609405.540687,"caller":"parser/parser.go:130","msg":"parsing document tree with root type: SLSA"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fa086f]

goroutine 149 [running]:
github.com/guacsec/guac/pkg/ingestor/parser/slsa.fillSLSA01(...)
	/Users/lumb/go/src/github.com/guacsec/guac/pkg/ingestor/parser/slsa/parser_slsa.go:199
github.com/guacsec/guac/pkg/ingestor/parser/slsa.(*slsaParser).getSLSA(0xc001fa4380)
	/Users/lumb/go/src/github.com/guacsec/guac/pkg/ingestor/parser/slsa/parser_slsa.go:235 +0xef
github.com/guacsec/guac/pkg/ingestor/parser/slsa.(*slsaParser).Parse(0xc001fa4380, {0xc0003e1fb0?, 0x250f72c?}, 0x4?)
	/Users/lumb/go/src/github.com/guacsec/guac/pkg/ingestor/parser/slsa/parser_slsa.go:82 +0x73
github.com/guacsec/guac/pkg/ingestor/parser.parseHelper({0x2792fa0, 0xc0002e7940}, 0xc0006a4240)
	/Users/lumb/go/src/github.com/guacsec/guac/pkg/ingestor/parser/parser.go:190 +0x83
github.com/guacsec/guac/pkg/ingestor/parser.(*docTreeBuilder).parse(0xc000629a48, {0x2792fa0, 0xc0002e7940}, 0xc0013fa260, 0x0?)
	/Users/lumb/go/src/github.com/guacsec/guac/pkg/ingestor/parser/parser.go:161 +0x5c
github.com/guacsec/guac/pkg/ingestor/parser.ParseDocumentTree({0x2792fa0, 0xc0002e7940}, 0xc0013fa260)
	/Users/lumb/go/src/github.com/guacsec/guac/pkg/ingestor/parser/parser.go:131 +0x19c
github.com/guacsec/guac/cmd/guacone/cmd.getIngestor.func1(0x2785a80?)
	/Users/lumb/go/src/github.com/guacsec/guac/cmd/guacone/cmd/files.go:255 +0x27
github.com/guacsec/guac/cmd/guacone/cmd.glob..func5.1.1()
	/Users/lumb/go/src/github.com/guacsec/guac/cmd/guacone/cmd/files.go:169 +0x2ef
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/lumb/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/lumb/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
```

**GUAC version**
Are you using a released version of GUAC or one build from a commit in the
repository?

**Ingested document(s)**

Can you share the documents that are used to reproduce the ingestion errors or showcase the data quality issues.

**Additional context**

**Comment by lumjjb** [comment]
Awesome! Assigned it to you! Thanks!!

**Comment by nathannaveen** [comment]
@lumjjb, I was writing a test for this issue, and then I saw:

https://github.com/guacsec/guac/blob/bc5c042429c7fa93f993cfef3a7ad2b5f4b1059c/pkg/ingestor/parser/slsa/parser_slsa.go#L212-L214

The if statement is checking whether `BuildFinishedOn` isn't equal to `nil`, but assigning `inp.FinishedOn` to `BuildStartedOn` instead of `BuildFinishedOn`. I assume that this is a bug in the code and it should be:

`inp.FinishedOn = stmt.Predicate.Metadata.BuildFinishedOn`

Instead of:

`inp.FinishedOn = stmt.Predicate.Metadata.BuildStartedOn`

Is my assumption correct?

**Comment by pxp928** [comment]
> @lumjjb, I was writing a test for this issue, and then I saw:
> 
> https://github.com/guacsec/guac/blob/bc5c042429c7fa93f993cfef3a7ad2b5f4b1059c/pkg/ingestor/parser/slsa/parser_slsa.go#L212-L214
> 
> The if statement is checking whether `BuildFinishedOn` isn't equal to `nil`, but assigning `inp.FinishedOn` to `BuildStartedOn` instead of `BuildFinishedOn`. I assume that this is a bug in the code and it should be:
> 
> `inp.FinishedOn = stmt.Predicate.Metadata.BuildFinishedOn`
> 
> Instead of:
> 
> `inp.FinishedOn = stmt.Predicate.Metadata.BuildStartedOn`
> 
> Is my assumption correct?

Yes that is correct! Good catch
