### ISSUE TITLE
Guac requirements are misleading

### ISSUE THREAD

**Issue by noah-de** [guacsec/guac#1068]
We place an unnecessary hurdle in front of users who are literally looking for a quick start.
https://docs.guac.sh/setup/#prerequisites
Has a list of requirements, that is essentially misleading.

The required version of Golang is 1.20+.
jq is not optional, it is a requirement.

I am new to this community and am not sure what the correct resolution would be, however, it does seem like a simple fix for the documentation to be corrected.

Edit: updated to be version 1.20+

**Comment by pxp928** [comment]
Marking this complete with merging of PR https://github.com/guacsec/guac-docs/pull/78
