### ISSUE TITLE
[bug] nil pointer when running `HasSBOM` query with no `hasSBOMSpec`

### ISSUE THREAD

**Issue by mrizzi** [guacsec/guac#1105]
**Describe the bug**
Executing this query
```
query HasSBOM {
  HasSBOM {
    uri
  }
}
```
causes a nil pointer on like `pkg/assembler/backends/inmem/hasSBOM.go:227`

**To Reproduce**

1. successfully ingest an SBOM into guac "inmem"
1. open Graphql playground in the browser
1. execute query reported above
1. See error

I'm going to add a test reproducer for this.

**Expected behavior**
Get a valid response with the list of the `uri` for the ingested SBOM.

**GUAC version**
latest `main` branch

**Additional context**
I'm going to open a PR sharing a test to reproduce this issue and also with a fix for this to be discussed.

**Comment by pxp928** [comment]
> In your scenario, I feel like the filter isn't nil but its fields are, so it's a slightly different scenario.
My query above, being without hasSBOMSpec, causes filter itself to be nil.

Yes, when I meant "query above" I was referring to your query:

```
query HasSBOM {
  HasSBOM {
    uri
  }
}
```

Sorry for the confusion.
