### ISSUE TITLE
[feature] Change mutation API to remove requirement to return all values except ID

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#1116]
**Is your feature request related to a problem? Please describe.**
Change mutation APIs to remove requirement to return the entire struct, but instead just IDs. This will make it so that mutations will have better execution time as usually results in INSERTs being used instead of UPSERTs with a followup retrieval if necessary.

A field is still required since GraphQL requires a return statement.

This stems from efforts in the https://github.com/guacsec/guac/pull/910, as well as some optimization efforts for implementation in ArangoDB.

**Describe the solution you'd like**

For each mutation like the following example for HasSBOM, go from
```

extend type Mutation {
  "Certifies that a package or artifact has an SBOM."
  ingestHasSBOM(subject: PackageOrArtifactInput!, hasSBOM: HasSBOMInputSpec!): HasSBOM!
  "Bulk ingest that package or artifact has an SBOM."
  ingestHasSBOMs(subjects: PackageOrArtifactInputs!, hasSBOMs: [HasSBOMInputSpec!]!): [HasSBOM!]!
}
```
to
```
extend type Mutation {
  "Certifies that a package or artifact has an SBOM."
  ingestHasSBOM(subject: PackageOrArtifactInput!, hasSBOM: HasSBOMInputSpec!): string!
  "Bulk ingest that package or artifact has an SBOM."
  ingestHasSBOMs(subjects: PackageOrArtifactInputs!, hasSBOMs: [HasSBOMInputSpec!]!): [string!]!
}
```

**Describe alternatives you've considered**

Return a boolean instead. However IDs are still usable. If the ID is not returnable, returning an empty string is also fine.

**Additional context**

**Comment by lumjjb** [comment]
FYI. @pxp928 @ivanvanderbyl @stevemenezes

**Comment by ivanvanderbyl** [comment]
Oh this would be neat for Postgres since upserts can only return IDs and currently require a separate query to fetch the actual record. However, bulk upserts still require a separate query.

**Comment by mihaimaruseac** [comment]
I'd say it should be `ID!` instead of `string!`.

**Comment by arorasoham9** [comment]
I can take this.

**Comment by mihaimaruseac** [comment]
Looking forward for a PR for this!

**Comment by arorasoham9** [comment]
@mihaimaruseac Could I please what specific files I should look at to get a better understanding of what needs changes?

**Comment by arorasoham9** [comment]
I took a look at this issue and have reached this understanding. The GraphQL mutations are to be edited to return a String! or a [String!]! and instead of returning the struct array or struct array in the resolvers, we return the string IDs.

**Comment by pxp928** [comment]
yes that is correct so all the changes need to happen here on the server side: https://github.com/guacsec/guac/tree/main/pkg/assembler/graphql/schema (for all that contain a mutation) and on the client side: https://github.com/guacsec/guac/tree/main/pkg/assembler/clients/operations

For the Server side, all mutations have to change to:

For Example:
```
extend type Mutation {
  "Certifies that a package or artifact has an SBOM."
  ingestHasSBOM(subject: PackageOrArtifactInput!, hasSBOM: HasSBOMInputSpec!): ID!
  "Bulk ingest that package or artifact has an SBOM."
  ingestHasSBOMs(subjects: PackageOrArtifactInputs!, hasSBOMs: [HasSBOMInputSpec!]!): [ID!]!
}
```

For Client side, all the mutations will change to expect a return of an ID:

For example: 
````
mutation IngestArtifact($artifact: ArtifactInputSpec!) {
  ingestArtifact(artifact: $artifact) {
    ID
  }
}

# Bulk Ingest Artifacts

mutation IngestArtifacts($artifacts: [ArtifactInputSpec!]!) {
  ingestArtifacts(artifacts: $artifacts) {
    ID
  }
}
```


After that you need to regenerate the code: `make generate`. This will most likely break a lot of the assembler, CLI and other...so that will have to be fixed to accept only IDs.

**Comment by arorasoham9** [comment]
That answered my queries as well. Thank you, @pxp928 . I'll try to send a PR soon.

**Comment by mihaimaruseac** [comment]
Sorry, been travelling. @pxp928 's answer is complete

**Comment by arorasoham9** [comment]
Could I get some insight on this error, please?
`operations/vulnEqual.graphql:22: query-spec does not match schema: Cannot query field "ID" on type "ID".`  
It appears when I run `go generate`

**Comment by pxp928** [comment]
What have you changed so far @arorasoham9? Based on that we can figure out where the error is coming from. Are you working on a branch that we can look at the diff?

**Comment by arorasoham9** [comment]
@pxp928  This is what I have for now https://github.com/arorasoham9/guac/commit/7a7c2c64ebfe4f4fdca4522d50b15d53feb5d326

**Comment by pxp928** [comment]
hmmm it's a strange error. @mihaimaruseac any thoughts why this would happen? I am looking into it more...

**Comment by arorasoham9** [comment]
https://stackoverflow.com/questions/56345757/cannot-query-field-id-on-type-createuser-with-official-graphql-tutorial
This could be it.

**Comment by arorasoham9** [comment]
I am guessing the fix is to use the spread operator like so.

`mutation IngestBuilder($builder: BuilderInputSpec!) {
  ingestBuilder(builder: $builder) {
    ...ID
  }
}`

**Comment by pxp928** [comment]
> I am guessing the fix is to use the spread operator like so.
mutation IngestBuilder($builder: BuilderInputSpec!) { ingestBuilder(builder: $builder) { ...ID } }

No this does not work.

**Comment by mihaimaruseac** [comment]
I think because we return a scalar we don't need anything in `{}`. So `mutation IngestBuilder($builder: BuilderInputSpec!) { ingestBuilder(builder: $builder) {}` (or maybe even without the `{}`?

**Comment by pxp928** [comment]
@arorasoham9 looks like just doing:

```
mutation IngestBuilder($builder: BuilderInputSpec!) {
  ingestBuilder(builder: $builder)
}
```
works

Thanks @mihaimaruseac!

**Comment by mihaimaruseac** [comment]
We'll need to update examples too, in case we look at the values generated from the ingestion

**Comment by arorasoham9** [comment]
Can I safely ignore these errors that appear after I run `make generate`?

`go generate ./...
validation failed: packages.Load: /home/vagrant/guac/pkg/assembler/graphql/resolvers/artifact.resolvers.go:16:9: cannot use r.Backend.IngestArtifact(ctx, artifact) (value of type *model.Artifact) as string value in return statement
/home/vagrant/guac/pkg/assembler/graphql/resolvers/artifact.resolvers.go:21:9: cannot use r.Backend.IngestArtifacts(ctx, artifacts) (value of type []*model.Artifact) as []string value in return statement
/home/vagrant/guac/pkg/assembler/graphql/resolvers/builder.resolvers.go:15:9: cannot use r.Backend.IngestBuilder(ctx, builder) (value of type *model.Builder) as string value in return statement
/home/vagrant/guac/pkg/assembler/graphql/resolvers/builder.resolvers.go:20:9: cannot use r.Backend.IngestBuilders(ctx, builders) (value of type []*model.Builder) as []string value in return statement
/home/vagrant/guac/pkg/assembler/graphql/resolvers/certifyBad.resolvers.go:15:9: cannot use r.Backend.IngestCertifyBad(ctx, subject, &pkgMatchType, certifyBad) (value of type *model.CertifyBad) as string value in return statement
/home/vagrant/guac/pkg/assembler/graphql/resolvers/certifyBad.resolvers.go:20:9: cannot use r.Backend.IngestCertifyBads(ctx, subjects, &pkgMatchType, certifyBads) (value of type []*model.CertifyBad) as []string value in return statement`

**Comment by mihaimaruseac** [comment]
I think so too.

**Comment by pxp928** [comment]
Yes you can update the resolver based on updating the backend interface.

**Comment by pxp928** [comment]
Re-opening issue as updates need to be made to the backends to only return the IDs (currently returning the actual model object)

**Comment by pxp928** [comment]
Marking this issue as complete and follow-up work will be done in the issues referenced above.

**Comment by mrizzi** [comment]
Worth having a branch in the repo (e.g. `1116-return-ID`) with the changes to `Backend` interface in `backends.go` and against which every backend can open PRs?
This should simplify the gathering of changes from all the backends.
Once done, `1116-return-ID` could be merged into `main` with no effort/breaking changes.

WDYT?

**Comment by pxp928** [comment]
sure that sounds good, here is the branch - https://github.com/guacsec/guac/tree/1116-return-ID

**Comment by mrizzi** [comment]
> sure that sounds good, here is the branch - https://github.com/guacsec/guac/tree/1116-return-ID

created https://github.com/guacsec/guac/pull/1285 for changing the `Backend` interface so that, once merged, all the backends can start with the implementations
