### ISSUE TITLE
[ingestion/data-quality issue] spdx sbom failiing to ingest

### ISSUE THREAD

**Issue by javixeneize** [guacsec/guac#1160]
Hi

I have a spdx file i am trying to ingest, and it is also failing

{"level":"fatal","ts":1692172845.5339441,"caller":"cmd/files.go:211","msg":"unable to ingest doc tree: unhandled PURL type: a-name","stacktrace":"github.com/guacsec/guac/cmd/guacone/cmd.glob..func5\n\t/Users/javi/Downloads/guac/cmd/guacone/cmd/files.go:211\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/javi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/javi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/javi/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/guacsec/guac/cmd/guacone/cmd.Execute\n\t/Users/javi/Downloads/guac/cmd/guacone/cmd/root.go:56\nmain.main\n\t/Users/javi/Downloads/guac/cmd/guacone/main.go:23\nruntime.main\n\t/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:250"}

I am using the example file provided by spdx, https://raw.githubusercontent.com/spdx/spdx-spec/development/v2.3.1/examples/SPDXJSONExample-v2.3.spdx.json

Is this version compatible with guac?

Thanks

**Comment by pxp928** [comment]
@javixeneize thanks for the report. I tried to ingest the example SDPX above and I did not get an error. Could you explain more about how you are running GUAC?

```
file:///../../../Desktop/SPDXJSONExample-v2.3.spdx.json
{"level":"info","ts":1692185743.8835552,"caller":"cmd/files.go:198","msg":"collector ended gracefully"}
{"level":"info","ts":1692185743.886817,"caller":"parser/parser.go:129","msg":"parsing document tree with root type: SPDX"}
{"level":"info","ts":1692185743.8885372,"caller":"cmd/files.go:178","msg":"unable to create entries in collectsub server, but continuing: unable to add collect entries: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:2782: connect: connection refused\""}
{"level":"info","ts":1692185743.88858,"caller":"helpers/bulk.go:34","msg":"assembling Package: 8"}
{"level":"info","ts":1692185743.890451,"caller":"helpers/bulk.go:45","msg":"assembling Source: 0"}
{"level":"info","ts":1692185743.890697,"caller":"helpers/bulk.go:57","msg":"assembling Artifact: 9"}
{"level":"info","ts":1692185743.891063,"caller":"helpers/bulk.go:68","msg":"assembling Materials (Artifact): 0"}
{"level":"info","ts":1692185743.89126,"caller":"helpers/bulk.go:74","msg":"assembling Builder: 0"}
{"level":"info","ts":1692185743.8915358,"caller":"helpers/bulk.go:85","msg":"assembling CVE: 0"}
{"level":"info","ts":1692185743.891784,"caller":"helpers/bulk.go:96","msg":"assembling OSV: 0"}
{"level":"info","ts":1692185743.8920152,"caller":"helpers/bulk.go:108","msg":"assembling GHSA: 0"}
{"level":"info","ts":1692185743.892234,"caller":"helpers/bulk.go:118","msg":"assembling CertifyScorecard: 0"}
{"level":"info","ts":1692185743.8922439,"caller":"helpers/bulk.go:123","msg":"assembling IsDependency: 5"}
{"level":"info","ts":1692185743.893492,"caller":"helpers/bulk.go:128","msg":"assembling IsOccurrence: 13"}
{"level":"info","ts":1692185743.894912,"caller":"helpers/bulk.go:133","msg":"assembling HasSLSA: 0"}
{"level":"info","ts":1692185743.894923,"caller":"helpers/bulk.go:139","msg":"assembling CertifyVuln: 0"}
{"level":"info","ts":1692185743.894927,"caller":"helpers/bulk.go:147","msg":"assembling IsVuln: 0"}
{"level":"info","ts":1692185743.894932,"caller":"helpers/bulk.go:156","msg":"assembling HasSourceAt: 0"}
{"level":"info","ts":1692185743.894936,"caller":"helpers/bulk.go:164","msg":"assembling CertifyBad: 0"}
{"level":"info","ts":1692185743.8949409,"caller":"helpers/bulk.go:170","msg":"assembling CertifyGood: 0"}
{"level":"info","ts":1692185743.894945,"caller":"helpers/bulk.go:177","msg":"assembling PointOfContact: 0"}
{"level":"info","ts":1692185743.8949492,"caller":"helpers/bulk.go:185","msg":"assembling HasSBOM: 1"}
{"level":"info","ts":1692185743.895394,"caller":"helpers/bulk.go:191","msg":"assembling VEX : 0"}
{"level":"info","ts":1692185743.895402,"caller":"helpers/bulk.go:199","msg":"assembling HashEqual : 0"}
{"level":"info","ts":1692185743.8960938,"caller":"helpers/bulk.go:205","msg":"assembling PkgEqual : 0"}
{"level":"info","ts":1692185743.896106,"caller":"cmd/files.go:189","msg":"[12.59ms] completed doc {Collector:FileCollector Source:file:///../../../Desktop/SPDXJSONExample-v2.3.spdx.json}"}
{"level":"info","ts":1692185743.896116,"caller":"cmd/files.go:217","msg":"completed ingesting 1 documents of 1"}
```

**Comment by javixeneize** [comment]
sure... im just running ./bin/guacone collect files ~/Downloads/SPDXJSONExample-v2.3.spdx.json

**Comment by pxp928** [comment]
So that is also what I did above. Are you building from the binaries from main?

**Comment by javixeneize** [comment]
yep, ~/Downloads/guac (main?) $ ./bin/guacone collect files ~/Downloads/SPDXJSONExample-v2.3.spdx.json

i am using a sillicon mac, if it is of any relevance

**Comment by pxp928** [comment]
are you also using docker-compose with the `make container` (similar to the demos steps)?

**Comment by pxp928** [comment]
Another way to bring up just the graphQL with the `inmem` database is running: `go run ./cmd/guacgql --gql-debug` and in another terminal window running: `./bin/guacone collect files ~/Downloads/SPDXJSONExample-v2.3.spdx.json`. That should also yield similar results.

**Comment by javixeneize** [comment]
thats strange... it works now... i will keep trying with other spdx files and if it fails again i will reopen the issue

thanks
