### ISSUE TITLE
[ingestion/data-quality issue] CyconeDX error with update for #976

### ISSUE THREAD

**Issue by joestein** [guacsec/guac#1166]
I am working off of trunk trying to get CycloneDX working with GUAC here is my SBOM https://gist.github.com/joestein/aa0218047e34c890e9939639da326261 and I am now getting a new error ( I am also using a SBOM that should work according to https://github.com/guacsec/guac/issues/976#issuecomment-1682196687 having added in the missing XML nodes that are missing in the CycloneDX 1.4 spec).

here is error now
`[charmalloc@Joes-MacBook-Pro guac % ./bin/guacone collect files ~/dev/elixir/course/live_view_studio/bom.xml
{"level":"info","ts":1692302126.225869,"caller":"cli/init.go:53","msg":"Using config file: /Users/charmalloc/dev/guac/guac.yaml"}
{"level":"info","ts":1692302126.22623,"caller":"cmd/files.go:198","msg":"collector ended gracefully"}
file:////Users/charmalloc/dev/elixir/course/live_view_studio/bom.xml
{"level":"info","ts":1692302126.229305,"caller":"parser/parser.go:129","msg":"parsing document tree with root type: CycloneDX"}
{"level":"info","ts":1692302126.2326741,"caller":"helpers/bulk.go:34","msg":"assembling Package: 55"}
{"level":"info","ts":1692302126.239635,"caller":"helpers/bulk.go:45","msg":"assembling Source: 0"}
{"level":"info","ts":1692302126.241211,"caller":"helpers/bulk.go:57","msg":"assembling Artifact: 54"}
{"level":"info","ts":1692302126.2431931,"caller":"helpers/bulk.go:68","msg":"assembling Materials (Artifact): 0"}
{"level":"info","ts":1692302126.243954,"caller":"helpers/bulk.go:74","msg":"assembling Builder: 0"}
{"level":"info","ts":1692302126.244739,"caller":"helpers/bulk.go:85","msg":"assembling Vulnerability: 0"}
{"level":"info","ts":1692302126.245425,"caller":"helpers/bulk.go:95","msg":"assembling CertifyScorecard: 0"}
{"level":"info","ts":1692302126.2454321,"caller":"helpers/bulk.go:100","msg":"assembling IsDependency: 54"}
{"level":"fatal","ts":1692302126.247413,"caller":"cmd/files.go:211","msg":"unable to assemble graphs: ingestIsDependencies failed with error: isDependencies failed with error: returned error 422 Unprocessable Entity: {\"errors\":[{\"message\":\"Unknown argument \\\"depPkgMatchType\\\" on field \\\"Mutation.ingestDependencies\\\".\",\"locations\":[{\"line\":3,\"column\":2}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}}],\"data\":null}","stacktrace":"github.com/guacsec/guac/cmd/guacone/cmd.glob..func5\n\t/Users/charmalloc/dev/guac/cmd/guacone/cmd/files.go:211\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/charmalloc/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/charmalloc/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/charmalloc/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/guacsec/guac/cmd/guacone/cmd.Execute\n\t/Users/charmalloc/dev/guac/cmd/guacone/cmd/root.go:56\nmain.main\n\t/Users/charmalloc/dev/guac/cmd/guacone/main.go:23\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}`

**Comment by pxp928** [comment]
Thanks for opening the issue @joestein. The `422 Unprocessable Entity` usually means the graphQL APIs are out of sync. Are you on the latest main?

**Comment by joestein** [comment]
I needed to-do make container again not just make build, my bad. It is working now.

`{"level":"info","ts":1692302659.295847,"caller":"cmd/files.go:217","msg":"completed ingesting 1 documents of 1"}`
