### ISSUE TITLE
[question] GUAC Visualizer

### ISSUE THREAD

**Issue by joestein** [guacsec/guac#1167]
I am getting a permission denied trying to clone GUAV Visualizer

`[charmalloc@Joes-MacBook-Pro guac % git clone git@github.com:guacsec/guac-visualizer.git
Cloning into 'guac-visualizer'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by pxp928** [comment]
hmmm...you can also `git clone https://github.com/guacsec/guac-visualizer.git` that should also work

**Comment by joestein** [comment]
That worked, I got my command from https://docs.guac.sh/guac-visualizer/#step-1-clone-the-guac-visualizer-repo

Thanks!
