### ISSUE TITLE
[feature] Move validation checks from backends to resolvers

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1179]
**Is your feature request related to a problem? Please describe.**
Currently, validation of the inputs is done at the individual backend. Some are located in the [helper directory](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/helper/validation.go) others are located in the inmem back end itself. For example: [certifyBad bulk ingestion input validation](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/inmem/certifyBad.go#L62-L83) and [vex staus input validation](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/inmem/certifyVEXStatement.go#L421-L432)

**Describe the solution you'd like**
All these need to be moved to the respective [resolvers](https://github.com/guacsec/guac/tree/main/pkg/assembler/graphql/resolvers).

The `inmem` backend also contains unit tests to test and validate these functions. These also need to be moved to the resolvers dir (unit test per file like normal)

**Describe alternatives you've considered**
Defining them in each backend requires unneeded code duplication.

**Comment by pxp928** [comment]
cc @jeffmendoza @mrizzi

**Comment by mrizzi** [comment]
@pxp928 @jeffmendoza I'm happy to work on this, is it ok for you guys?
If yes, should I assign this issue to me?

**Comment by pxp928** [comment]
Sounds good! Thanks @mrizzi
