### ISSUE TITLE
[bug] Unstable `Test_depsCollector_RetrieveArtifacts/wheel-axle-runtime_pypi_package` test

### ISSUE THREAD

**Issue by mrizzi** [guacsec/guac#1193]
**Describe the bug**

`wheel-axle-runtime@0.0.4.dev20230415195356` package changes its dependencies on deps.dev every time a new `filelock` version is released.

It happened once on August 29th 2023 in https://github.com/guacsec/guac/actions/runs/6010856945/job/16303132005?pr=1185#step:6:1628 after `filelock@3.12.3` was released on August 28, 2023

It has been worarounded once in https://github.com/guacsec/guac/pull/1192 but it will happen again as soon as dependencies will change again.

**To Reproduce**

It depends on  `wheel-axle-runtime`'s dependencies to change in order to be reproduced.

**Expected behavior**
A stable and reproducible test.

**Screenshots**

**GUAC version**
`main` branch

**Additional context**
Workaround available: update the expected result like done in https://github.com/guacsec/guac/pull/1192

**Comment by pxp928** [comment]
Brittle test that needs to be updated found here - https://github.com/guacsec/guac/blob/main/pkg/handler/collector/deps_dev/deps_dev_test.go#L56-L249

**Comment by pxp928** [comment]
An option might be to ignore the dependency output during the validation.
