### ISSUE TITLE
[feature - inmem] Change all backend mutation implementations to return only ID

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1196]
**Is your feature request related to a problem? Please describe.**
Followup to issue https://github.com/guacsec/guac/issues/1116. Now that the graphQL mutation  API has been updated, the [backend](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/backends.go) needs to be updated to only return the IDs based on the revised [resolvers](https://github.com/guacsec/guac/tree/main/pkg/assembler/graphql/resolvers)

**Describe the solution you'd like**

Multiple issues will be created for each backend update. This issue will focus on the updates to the [inmem](https://github.com/guacsec/guac/tree/main/pkg/assembler/backends/inmem) backend. 

All mutations must be changed to return only ID (string). 

For example for artifacts:

```
IngestArtifact(ctx context.Context, artifact *model.ArtifactInputSpec) (string, error)
IngestArtifacts(ctx context.Context, artifacts []*model.ArtifactInputSpec) ([]string, error) 
```

Must both be updated in the [backend interface](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/backends.go#L54-L55) and in the [inmem backend](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/inmem/artifact.go#L102-L116)

Unit tests must be updated as needed to reflect these changes

**Comment by pxp928** [comment]
FYI @j-white this will also need to be done on the gremlin backend. We can get that merged in as a WIP backend (similar to arango and ENT) and the community can help make updates as needed :)

**Comment by shafeeshafee** [comment]
I'm going to help out with this.
