### ISSUE TITLE
[Optimization] In-mem getPackageIDFromInput

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#1234]
There's a function for retrieval of packages in [getPackageIDFromInput](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/inmem/pkg.go#L656), which I hypothesize is causing some slow down in the ingestion for in-mem backend.

I suspect that the issue is within the [version loop](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/inmem/pkg.go#L674-L688). If this can be optimized into a hash map, that would be great.

**Comment by lumjjb** [comment]
@mdeicas could be a cool issue to look at as well :)

**Comment by neilnaveen** [comment]
Could I work on this issue if @mdeicas has not started yet?

**Comment by neilnaveen** [comment]
@lumjjb 

- What was the test data you used?

- I would like to run a profiler to find the specific bottlenecks.

**Comment by mdeicas** [comment]
I've already started this @neilnaveen, sorry!

**Comment by lumjjb** [comment]
Fixed by #1332
