### ISSUE TITLE
IdentityFor edge should be generic

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#128]
The identity for edge should apply to almost any type of document/node, and thus should be able to be defined on any GuacNode. This should be done as well as any other clean up required around identity for graphBuilder

**Comment by pxp928** [comment]
Based on old architecture. Identity is still being worked on in the new re-architecture via GraphQL. Related to issue https://github.com/guacsec/guac/issues/217 and https://github.com/guacsec/guac/issues/75
