### ISSUE TITLE
Confusing name of field in IsDependency GraphQL

### ISSUE THREAD

**Issue by mdeicas** [guacsec/guac#1293]
The GraphQL types [`IsDependency`](https://github.com/guacsec/guac/blob/249fdd6a381e60b6123c5a5e9713b73620c101c8/pkg/assembler/graphql/schema/isDependency.graphql#L30C1-L31C1) and [`IsDependencySpec`](https://github.com/guacsec/guac/blob/249fdd6a381e60b6123c5a5e9713b73620c101c8/pkg/assembler/graphql/schema/isDependency.graphql#L57) both contain the fields `package` and `dependentPackage`. These fields are related by `package` being dependent on `dependentPackage`. In other words, `package` is a dependent and `dependentPackage` is a dependency. I think that the naming of `dependentPackage` is opposite to what it represents, and would be better served by something like `dependencyPackage`. 

As an example to where confusion might arise, the current naming result in a GraphQL query for dependency packages to be a list of `dependentPackage`'s.

**Comment by pxp928** [comment]
@mdeicas agree it would make more sense.

**Comment by lumjjb** [comment]
+1 probably makes sense to have this renamed before 0.2? I'll add the milestone

**Comment by desmax74** [comment]
I can take this issue.
