### ISSUE TITLE
[feature] Drop the nightly release

### ISSUE THREAD

**Issue by sudo-bmitch** [guacsec/guac#1298]
**Is your feature request related to a problem? Please describe.**
Nightly releases spam the notifications of those that want to only watch the project for important updates.

**Describe the solution you'd like**
Switch to a nightly build without a release, giving users a tag to test, and artifacts if you want to expose binaries too.

**Describe alternatives you've considered**
Removing my watch on the project.

**Additional context**
This is just my personal opinion, so feel free to ignore it. But it feels like something that will hurt casual engagement with the project.

**Comment by pxp928** [comment]
Per the community call, there was interest in having snapshots between releases instead of nightly releases. cc @dejanb

**Comment by lumjjb** [comment]
hmm - i think one of the appealing parts of a nightly "thing" is also having the built artifacts that users can use. I'm wondering if editing a release will be triggered in a watch?

**Comment by sunnyyip** [comment]
That's what I was thinking as well - reuse the release and simply replace the artifacts underneath it - to avoid triggering notification. We need to test 
1. if this will trigger notification since the release got updated
2. if overwriting individual artifact is even possible

**Comment by sudo-bmitch** [comment]
You can generate artifacts without running a release.
https://github.com/actions/upload-artifact

**Comment by lumjjb** [comment]
@sudo-bmitch closing this for now since we've paused it, and if our new solution makes noise again, please do poke us again!

**Comment by sudo-bmitch** [comment]
@lumjjb thank you!
