### ISSUE TITLE
Promote @mrizzi to "Reviewer"

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#1310]
Looking at the [Contributor Ladder](https://github.com/guacsec/guac/blob/main/CONTRIBUTING.md#reviewer)
> 

Reviewer | Review contributions from other members | Prove technical expertise in at least one GUAC topic area | Can approve PRs | Write
-- | -- | -- | -- | --

> Once a community participant has demonstrated expertise in one GUAC topic area, owners and/on maintainers can propose graduating the community participant to the next role, that of Reviewer.
> A reviewer will be responsible of reviewing contributions from other contributors that touch the corresponding topic area. They should ensure that the PRs are adequately tested, follow the guidelines for the specific topic area.

We propose promoting @mrizzi to the level of "Reviewer". Marco has shown expertise in the area of "Backends" (ent), and has agreed to the above responsibilities of the level.

This issue is serving as that proposal for approval consensus.
cc @mlieberman85 @mihaimaruseac @lumjjb  @pxp928 @SantiagoTorres @rgreinho @jeffmendoza

**Comment by mihaimaruseac** [comment]
LGTM

**Comment by lumjjb** [comment]
LGTM!

**Comment by pxp928** [comment]
LGTM!

**Comment by dejanb** [comment]
+1 (non-binding)

**Comment by mlieberman85** [comment]
LGTM!

**Comment by jeffmendoza** [comment]
LGTM!

**Comment by jeffmendoza** [comment]
@mrizzi Congrats, the majority has voted you in! We don't have a list anywhere for Reviewers. Can you add one with yourself? Probably at the end of the CONTRIBUTING.md makes sense.


Also, I've opened #1323 to clarify that the vote for Reviewers is the same as Owners.

**Comment by mrizzi** [comment]
> @mrizzi Congrats, the majority has voted you in! We don't have a list anywhere for Reviewers. 

Thanks a lot everyone, really happy for this :tada: 

>Can you add one with yourself? Probably at the end of the CONTRIBUTING.md makes sense.

Sure! Done in https://github.com/guacsec/guac/pull/1327

> Also, I've opened #1323 to clarify that the vote for Reviewers is the same as Owners.
