### ISSUE TITLE
[ingestion/data-quality issue] Support PACKAGE_OF relations in SPDX files 

### ISSUE THREAD

**Issue by dejanb** [guacsec/guac#1331]
Currently, a dependency of the package while parsing SPDX SBOM is determined by `DEPENDENCY_OF` and `CONTAINS` relations. The `PACKAGE_OF` relation is also found in SPDX files to define packages of the SBOM.

**Comment by lumjjb** [comment]
hmm, i'm not too familiar with this relationship, is this usually a `SpdxPackage PACKAGE_OF SpdxPackage`. Do you have an example?

Looking at the [recent SPDX audit of relationships](https://docs.google.com/spreadsheets/d/1yb49TkcR_dVEH_k_iOcBjNZbYDjkmd0HVweIuDpS9eg/edit#gid=2026590090), it looks like this one is marked as obselete. I'd be curious to know if its being used!

**Comment by dejanb** [comment]
Here's the example for the reference https://github.com/trustification/trustification/blob/main/integration-tests/tests/testdata/correlation/stf-1.5.json#L22567

It is used to define what containers are part of the "app"/"product". I'm not sure if that's the right use of it, but it's a use case we are trying to support.
