### ISSUE TITLE
Data race in pkg/collectsub/datasource/csubsource

### ISSUE THREAD

**Issue by mdeicas** [guacsec/guac#1335]
**Describe the bug**
There is a data race in `pkg/collectsub/datasource/csubsource` as seen in the failing unit tests of #1333.  

**To Reproduce**
Upgrade to go 1.21 and run `make test`. 

**GUAC version**
The CI uses the latest commit, and the bug can be reproduced with the same. 

**Additional context**
Although the data race is not detected by `make test` with go version 1.19, it can still be reproduced with 1.19 by running the package tests manually: run `go test -race -count=2` in the directory`pkg/collectsub/datasource/csubsource`.

**Comment by pxp928** [comment]
good catch @mdeicas
