### ISSUE TITLE
[bug] Scorecard certifier does not work

### ISSUE THREAD

**Issue by mdeicas** [guacsec/guac#1364]
**Describe the bug**
The scorecard certifier produces errors and does not appear to ingest any scorecard information into Guac. 

**To Reproduce**
1. Create an SBOM that has packages on deps.dev. For example, `syft -o spdx-json --file sbom.json [a golang executable]`. I used [golangci-lint-1.54.2-linux-amd64](https://github.com/golangci/golangci-lint/releases/tag/v1.54.2)
2. Ingest the SBOM : `guacone collect files sbom.json`
3. Run the deps.dev collector to ingest source information: `guaccollect deps_dev --service-poll=false`
4. Run the scorecard certifier: `guacone certifier scorecard`

There are numerous log messages indicating errors, such as this one: 
>  {"level":"error","ts":1696625875.519074,"caller":"cmd/scorecard.go:135","msg":"certifier ended with error: error getting scorecard result: error, failed to get clients: error making github repo: error during parse: invalid repo flag: nosnakecase. Expected full repository url","stacktrace":"github.com/guacsec/guac/cmd/guacone/cmd.glob..func11.3\n\t/home/runner/work/guac/guac/cmd/guacone/cmd/scorecard.go:135\ngithub.com/guacsec/guac/pkg/certifier/certify.generateDocuments\n\t/home/runner/work/guac/guac/pkg/certifier/certify/certify.go:149\ngithub.com/guacsec/guac/pkg/certifier/certify.Certify.func1\n\t/home/runner/work/guac/guac/pkg/certifier/certify/certify.go:77\ngithub.com/guacsec/guac/pkg/certifier/certify.Certify\n\t/home/runner/work/guac/guac/pkg/certifier/certify/certify.go:99\ngithub.com/guacsec/guac/cmd/guacone/cmd.glob..func11.4\n\t/home/runner/work/guac/guac/cmd/guacone/cmd/scorecard.go:146"} ...

Although there are scorecard nodes in the Guac instance, I think that they all come from the deps.dev collector. In cases where deps.dev does not have scorecard information on a package, the scorecard certifier should be able generate a scorecard report, but it does not. 

**GUAC version**
v0.2.0 

**Additional context**
I believe the error is due to incorrectly constructing the repository name [here](https://github.com/guacsec/guac/blob/2c19f256a0bcb5d2f66b8c1f4aa179948e847e8a/pkg/certifier/components/source/source.go#L86)

**Comment by pxp928** [comment]
Nice find @mdeicas

**Comment by pxp928** [comment]
FYI @nathannaveen, this might be of interest to you if you want to fix?

**Comment by nathannaveen** [comment]
@pxp928 I will work on this.

**Comment by nathannaveen** [comment]
I tried to reproduce the error:
* I am using guac v0.3.0
* Here is the sbom I used: https://gist.github.com/nathannaveen/778a34e80ed8a240aaea005e64ead022.
* I then ran `guaccollect deps_dev --service-poll=false` with the docker compose.
* But when I run `guacone certifier scorecard` it ended gracefully:

```
{"level":"info","ts":1697464465.270111,"caller":"cli/init.go:53","msg":"Using config file: /Users/nathannaveen/go/src/github.com/nathannaveen/guac/guac.yaml"}
{"level":"info","ts":1697464465.277668,"caller":"cmd/scorecard.go:135","msg":"certifier ended gracefully"}
{"level":"info","ts":1697464465.277704,"caller":"cmd/scorecard.go:160","msg":"All certifiers completed"}
{"level":"info","ts":1697464465.27772,"caller":"cmd/scorecard.go:168","msg":"completed ingesting 0 documents"}
```

**Comment by mdeicas** [comment]
Hmm I am still able to reproduce the error, here are my steps in more detail, using the sbom you provided: 

- download guac-compose and guacone from the [`v0.3.0`](https://github.com/guacsec/guac/releases/tag/v0.3.0) release page, and rename the binary to `guacone`
- in the guac-compose folder, run `docker compose up` 
- `./guacone collect files sbom.json`
- (The deps.dev collector is running is in polling mode, so it should run here)
- `./guacone certifier scorecard`

I get the same errors: 
> {"level":"error","ts":1697470368.5064006,"caller":"cmd/scorecard.go:138","msg":"certifier ended with error: error getting scorecard result: error, failed to get clients: error making github repo: error during parse: invalid repo flag: nosnakecase. Expected full repository url" 
...


What results do you get here?

**Comment by nathannaveen** [comment]
@mdeicas, Sorry for the late reply.

Thank you for the detailed steps. I am now receiving the same error as you!
