### ISSUE TITLE
[bug] Contributing page has broken links

### ISSUE THREAD

**Issue by lee0c** [guacsec/guac#1366]
**Describe the bug**
The [Contributing.md](https://github.com/guacsec/guac/blob/main/CONTRIBUTING.md#how-to-contribute) file has several dead links in the first section

**To Reproduce**

1. Go to Contributing.md
2. Click through either of the links in the first section

**Expected behavior**
Links should lead to documentation as expected

**GUAC version**
n/a irrelevant

**Comment by pxp928** [comment]
Thanks for the bug report @lee0c! I believe these got moved to [guac-docs](https://docs.guac.sh/). We will fix those!
