### ISSUE TITLE
[bug] Failing test (but appears to pass)

### ISSUE THREAD

**Issue by mdeicas** [guacsec/guac#1378]
**Describe the bug**
The test named `wheel-axle-runtime pypi package` in [`deps_dev_test.go`](https://github.com/guacsec/guac/blob/583c478b6d73395af9b9bcda151db3f973a3576c/pkg/handler/collector/deps_dev/deps_dev_test.go#L88C1-L89C1) currently passes because the comparison of actual output and expected output in this test does not cover some cases. The actual output is only checked against the expected output if the output list [is not empty](https://github.com/guacsec/guac/blob/583c478b6d73395af9b9bcda151db3f973a3576c/pkg/handler/collector/deps_dev/deps_dev_test.go#L230C2-L230C2). 

Checking equality of the lengths of the expected and actual lists, like [here](https://github.com/mdeicas/guac/blob/fc3a4f2e9579a1e488c15a6f3b031060fc7efaaf/pkg/handler/collector/deps_dev/deps_dev_test.go#L230C1-L232C5), results in the test failing. 

**To Reproduce**
Add better expected vs actual output comparison, like [here](https://github.com/mdeicas/guac/blob/fc3a4f2e9579a1e488c15a6f3b031060fc7efaaf/pkg/handler/collector/deps_dev/deps_dev_test.go#L230C1-L232C5), and run the test. 

**Expected behavior**
The test should fail. 

**GUAC version**
Almost the latest commit, 09c5879

**Comment by pxp928** [comment]
fixed with https://github.com/guacsec/guac/pull/1400
