### ISSUE TITLE
[feature] Define edges between package related nodes

### ISSUE THREAD

**Issue by mrizzi** [guacsec/guac#1381]
**Is your feature request related to a problem? Please describe.**

This refers to `Path` and `Neighbors` endpoints.

Assume these steps are executed:

1. 2 packages are ingested into guac: the have the same package type, namespace and name (e.g. `foo`) but two different versions (e.g. `v1` and `v2`)
1. add a vulnerability and certify vuln attached to only one version (e.g. `v1`)
1. `Path` query using with `subject` the CertifyVuln node ID and `target` the not vulnerable version will return a path that goes through the vulnerable version (i.e. `v1`), "up" to the package name (i.e. `foo`) and then "down" to the not vulnerable package (i.e. `v2`)

**Describe the solution you'd like**

It would be great to have available the edge definitions in GraphQL schema also for edges between package nodes in order to be able to filter them just like it can be done for most of the other edges.

**Describe alternatives you've considered**

The alternative is for the client to consume the `Path` endpoint response and filter on its own the package related edges.

**Additional context**
Slack discussion https://openssf.slack.com/archives/C03U677QD46/p1696951871139889)

**Comment by mrizzi** [comment]
I think this should be considered also for the impact on performances that the lack of the references for the edges within each trie has.

Using the same example in the description, if the `Path` query is invoked with `subject` the vulnerable versions `v1` and `target` the CertifyVuln node ID, then `brf` algorithm will go to the `v1`'s package name and from there up to the package namespace and also the package type and then down again, basically traversing the whole set of packages tries.

If the traversal of the package "version-name" edge could be avoided (having the edge and not adding it to the `usingOnly` array), then `brf` would stay "outside" of the package trie itself.

Although this could be done on the client-side, the impact on the `Path` query endpoint is huge server-side so being able to filter out package trie's edges would improve the performances.

**Comment by pxp928** [comment]
As per the discussion in the community meeting. Adding the edges related to package trie, source trie, and vulnerability trie should be fairly straightforward. I vote to add this to the existing: https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/schema/path.graphql#L64

@mihaimaruseac was there a reason we did not do this in the first place?

**Comment by mihaimaruseac** [comment]
I think we had them at the beginning but the issue was that now you'd be able to go from any package to any package by just going up the trie and then down.

**Comment by pxp928** [comment]
@mrizzi did you start the work on this? Does it make sense to have a discussion about how to move forward with this?

**Comment by mrizzi** [comment]
I didn't start yet but I'm happy work on it, open a draft PR and discuss on the code (if it's fine for you).
