### ISSUE TITLE
[bug] docker-compose.yaml starts postgres but does not use it.

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#1386]
**Describe the bug**
docker-compose.yaml starts postgres but does not use it.

**To Reproduce**

1. Download [guac-compose.tar.gz](https://github.com/guacsec/guac/releases/download/v0.2.0/guac-compose.tar.gz)
2. compose up

**Expected behavior**
Only start containers needed

**GUAC version**
v0.2.0

**Additional context**

We should have an easy way to compose-up with postgres/arango when those are ready. For now don't start it with the released compose yaml.

ALSO: The image name used is `postgres`, and should be `docker.io/library/postgres` for podman compatability.

**Comment by desmax74** [comment]
I can take this issue.

**Comment by pxp928** [comment]
we can create a follow-on issue for better/ more configurable way to bring up the proper backends once ready for use.
