### ISSUE TITLE
[bug] guacone certifier osv -p not working

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#1387]
**Describe the bug**
`guacone certifier osv -p` not working

**To Reproduce**

1. Setup GUAC with https://docs.guac.sh/setup/ or by hand and run `guacone certifier osv -p`
2. See that no vulns are ingested
3. Try `guacone certifier osv` without poll and see that it works

**Expected behavior**
Vulns ingested

**GUAC version**
v0.2.0

**Additional context**

Adding another bug to this: `guacone certifier osv -p` will not exit with `Ctrl-C`, it is hanging.

**Comment by pxp928** [comment]
So it works based on reproducing this bug, with polling set to false. With polling, it seems does not proceed past this loop:
https://github.com/guacsec/guac/blob/main/pkg/certifier/certify/certify.go#L104-L119 and never ingests the data.

**Comment by pxp928** [comment]
cc @mrizzi looks like we introduced this in this change: https://github.com/guacsec/guac/pull/1309/files

**Comment by pxp928** [comment]
we could do something like this: https://github.com/guacsec/guac/blob/main/pkg/certifier/components/root_package/root_package.go#L82-L122
where we capture the packages until a certain threshold. We add this in the emit functionality in the osv cli
