### ISSUE TITLE
[bug] ID returned when ingesting packages is incorrect

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#1414]
**Describe the bug**
When ingesting packages, the ID returned is the top-level ID (package type) and not the  lowest level ID (package version)

https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/resolvers/package.resolvers.go#L19
https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/resolvers/package.resolvers.go#L28

**To Reproduce**

Ingest packages using GQL, note id returned

**Expected behavior**
Should be the lowest level ID (package version node id)

**GUAC version**
head

**Comment by jeffmendoza** [comment]
Note, whenever we change the backend interface to return ID and not extract it here in the resolver, this code will be obsoleted.

**Comment by pxp928** [comment]
This was also caught in the PR by @knrc. This is changing to now return a flat struct of pkg IDs: https://github.com/guacsec/guac/pull/1367#discussion_r1361159400
