### ISSUE TITLE
[feature] Explore ent cache

### ISSUE THREAD

**Issue by naveensrinivasan** [guacsec/guac#1415]
**Is your feature request related to a problem? Please describe.**
The ent has a cache https://entgo.io/blog/2021/10/14/introducing-entcache/

**Describe the solution you'd like**
Explore if it is a viable option

**Comment by mrizzi** [comment]
@naveensrinivasan thanks for the issue :+1: 

While working on some performance issue with Ent some weeks ago, I looked into this cache and I gave it a quick try with no big success.

I didn't dig deeply into the issue but entcache v0.1.0 is based upon ent v0.11.2 but ent has already reached v0.12.4 so it looks like entcache isn't maintained that much right now.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan thanks for the issue 👍
> 
> While working on some performance issue with Ent some weeks ago, I looked into this cache and I gave it a quick try with no big success.
> 
> I didn't dig deeply into the issue but entcache v0.1.0 is based upon [ent v0.11.2](https://github.com/ariga/entcache/blob/v0.1.0/go.mod#L6) but ent has already reached v0.12.4 so it looks like entcache isn't maintained that much right now.

Thanks for the update! I appreciate the details.

So do you think we should close this issue?

**Comment by mrizzi** [comment]
Maybe worth asking to the entcache team if they have any plan to keep maintaining it.
I can do it and then we can decide what to do with this issue based on their reply.

**Comment by mrizzi** [comment]
https://github.com/ariga/entcache/issues/32

**Comment by mrizzi** [comment]
After almost two months with no answer, I think it's fine to close this
