### ISSUE TITLE
[bug] MAX_CONCURRENT_JOBS is no longer being used

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1433]
**Describe the bug**
The environment variable `"MAX_CONCURRENT_JOBS"` is no longer being utilized in [guacone collect files](https://github.com/guacsec/guac/blob/main/cmd/guacone/cmd/files.go#L44). This was utilized to allow the concurrency and allow the backend to process multiple files simultaneously. This functionality was removed in: https://github.com/guacsec/guac/pull/1195

**To Reproduce**

1. set `export MAX_CONCURRENT_JOBS=3`
2. run `go run ./cmd/guacone collect files ../guac-data/top-dh-sboms`

**Expected behavior**
Based on the value set for `MAX_CONCURRENT_JOBS`, it should concurrently try to ingest multiple documents 

**GUAC version**
main and v0.3.0

**Comment by pxp928** [comment]
Based on testing, this may no longer be a viable option for the `inmem` backend as it will cause concurrent map read and map write.

**Comment by lumjjb** [comment]
For now should we just remove this option for now? and we can decide later on if we want to have it again? or is this still being used in some other context?

**Comment by pxp928** [comment]
Yeah we should just remove the option as its not being used.

**Comment by arorasoham9** [comment]
I'll work on this

**Comment by pxp928** [comment]
We have batch processing in place. So this is no longer needed.
