### ISSUE TITLE
[bug] Inconsistent behavior in QueryVulnsViaVulnNodeNeighbors

### ISSUE THREAD

**Issue by nathannaveen** [guacsec/guac#1441]
## Description

When running the command `guacone query vuln "pkg:guac/spdx/ghcr.io/guacsec/vul-image-latest" --vuln-id "ghsa-7rjr-3q55-vv33" --search-depth 1 --num-path 1`, it sometimes fails with the error message: 

```
"level":"fatal","ts":1698673615.8497112,"caller":"cmd/vulnerability.go:123","msg":"error querying neighbor: error certify vulnerability node not found, incomplete data. Please ensure certifier has run"
```

This error occurs because the node ID passed as the `vulnerabilityNodeID` parameter in `QueryVulnsViaVulnNodeNeighbors` is not a `*model.NeighborsNeighborsCertifyVuln`. https://github.com/guacsec/guac/blob/b178fcd705990574f704a72ddde82e2dfb6c8948/cmd/guacone/cmd/vulnerability.go#L332-L342.

The problem stems from the fact that multiple IDs are available, but only the first one, `vulnResponse.Vulnerabilities[0].VulnerabilityIDs`, is being passed. The command's inconsistent behavior is due to the first ID not being a `*model.NeighborsNeighborsCertifyVuln`.

https://github.com/guacsec/guac/blob/b178fcd705990574f704a72ddde82e2dfb6c8948/cmd/guacone/cmd/vulnerability.go#L117-L121

## Expected Behavior
The function `QueryVulnsViaVulnNodeNeighbors` should be able to handle multiple IDs from `vulnResponse.Vulnerabilities[0].VulnerabilityIDs` and not just the first one. This would ensure consistent behavior and accurate vulnerability querying.

## Steps to Reproduce
1. Run the command `guacone query vuln "pkg:guac/spdx/ghcr.io/guacsec/vul-image-latest" --vuln-id "ghsa-7rjr-3q55-vv33" --search-depth 1 --num-path 1`.
2. Observe the inconsistent behavior and occasional failure with the error message mentioned above.

## Possible Solution
A possible solution could be to iterate over all the IDs in `vulnResponse.Vulnerabilities[0].VulnerabilityIDs` and pass them to `QueryVulnsViaVulnNodeNeighbors` instead of just using the first one. This would ensure that all available IDs are used and could potentially solve the issue.

**Comment by pxp928** [comment]
Hey @nathannaveen so this is not a bug. That error message occurs because the osv certifier has not completed running on all the dependency packages to make them with a certifyVuln (if even they have no vulnerability). If you look in the documentation: https://docs.guac.sh/querying-via-cli/#step-3-run-the-query-vulnerability-cli this message is something that we speak about. 

> A possible solution could be to iterate over all the IDs in vulnResponse.Vulnerabilities[0].VulnerabilityIDs and pass them to QueryVulnsViaVulnNodeNeighbors instead of just using the first one. This would ensure that all available IDs are used and could potentially solve the issue.

Yes this should iterate over all `vulnResponse.Vulnerabilities`, not just the first one as a vulnerability ID may be defined with another type (for example as `osv` and `cve`). In that case, we would want to check both.

**Comment by nathannaveen** [comment]
@pxp928 OK I see, thanks for the clarification! 

I will leave this issue open since we should still be iterating over all `vulnResponse.Vulnerabilities`.
