### ISSUE TITLE
[feature] Automate Swagger Doc Generation

### ISSUE THREAD

**Issue by nathannaveen** [guacsec/guac#1504]
Currently the Swagger docs for the REST endpoint are generated manually with `swag init -g **/**/*.go`. This should instead be automated in the Makefile.

https://github.com/guacsec/guac/blob/1e5a333697740afe0563eeefc3b11a2e0e1a8b26/cmd/guacrest/main.go#L44-L57

Generating from: https://github.com/swaggo/swag

**Comment by nathannaveen** [comment]
I will work on this.

**Comment by lumjjb** [comment]
while you're looking at this - would you check if there's a flag that allows the addition of the copyright header as well?

**Comment by nathannaveen** [comment]
> while you're looking at this - would you check if there's a flag that allows the addition of the copyright header as well?

Could you elaborate? I don't understand what you mean by copyright header. 

If you are saying that there should be a header for the swagger docs, then I don't think there are copyright headers for the actual docs.

**Comment by nathannaveen** [comment]
Closing because of https://github.com/guacsec/guac/issues/1544
