### ISSUE TITLE
[bug] guacone query vuln hangs

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#1561]
**Describe the bug**
guacone query vuln does not return

```
[jeffm@fedora guac]$ go run ./cmd/guacone query vuln "pkg:guac/spdx/ghcr.io/guacsec/vul-image-latest"
{"level":"info","ts":1701983654.642494,"caller":"logging/logger.go:70","msg":"Logging at info level"}
{"level":"info","ts":1701983654.6425474,"caller":"cli/init.go:67","msg":"Using config file: /home/jeffm/git/guac/guac.yaml"}
  C-c C-csignal: interrupt
[jeffm@fedora guac]$ 
```

**To Reproduce**

1. Startup guac, must include nats/ingestor/csub with deps.dev collector. If just running gql only, the hang will not happen
2. `guacone collect files ../guac-data/docs/`
4. `guacone certifier osv --poll=false`
5. `guacone query vuln "pkg:guac/spdx/ghcr.io/guacsec/vul-image-latest"`

**Expected behavior**
command returns

**GUAC version**
head

**Additional context**
Seems like a deadlock, as CPU is 0 (an infinite loop would use a lot of cpu).

**Comment by ridhoq** [comment]
I believe I ran into this when testing #1540

**Comment by pxp928** [comment]
It seems not to happen all the time but after a few attempts to run `
guacone query vuln "pkg:guac/spdx/ghcr.io/guacsec/vul-image-latest"`, it does cause a deadlock with the `go run ./cmd/guacingest`. It looks like it gets locked up by the graphQL server.
