### ISSUE TITLE
[bug] Resolver should check DependencyType enum for isDependency ingestion and queries

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#1604]
Todo:

Update [isDependency.resolvers.go](https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/resolvers/isDependency.resolvers.go) to check validity of [DependencyType](https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/schema/isDependency.graphql#L21) enum on ingestion, and on query if specified.

Backend behavior can be undefined, as the resolver will handle the validation

Original question:

## Question

[DependencyType is an enum](https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/schema/isDependency.graphql#L20-L28) . When a [query is made](https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/schema/isDependency.graphql#L78-L81) and [dependencyType is specified in the query spec](https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/schema/isDependency.graphql#L62). What should be done if the value passed is not one of the enum values?

a. Should a backend return nothing: does not match any nodes?

b. Should the backend correct any random string to "UNKNOWN" and return all deps that match unknown?

c. Should the backend return an error?

Similar question for an ingestion, ex: blank string.

**Comment by mlieberman85** [comment]
C. I personally think anything that doesn't fit an enum or other constraints should be an error. Generated client code should ensure that nothing invalid should get passed in normal operation. Calling the GQL API directly with something invalid I think should return an error.

**Comment by mihaimaruseac** [comment]
I would say invalid inputs should return both error and null result. GQL can return both at the same time. If error cannot be determined, only the null result would be returned.

**Comment by jeffmendoza** [comment]
Sounds good, updated this issue.

**Comment by mihaimaruseac** [comment]
Updated text looks good, it is indeed better to have resolver handle the conversion (somehow I thought the enums would be converted from strings to valid value or error already) and then backend can assume only correct inputs are given
