### ISSUE TITLE
Do Not Overwrite collectors

### ISSUE THREAD

**Issue by naveensrinivasan** [guacsec/guac#1616]
Do not overwrite collectors https://github.com/guacsec/guac/blob/7176dec30b6040d81df8b72c934c23fae6432c8c/pkg/handler/collector/collector.go#L59-L67

              re your [comment](https://github.com/guacsec/guac/pull/1500#issuecomment-1846097866) on this breaking things - is this behavior of overriding being used anywhere besides in tests? My initial thought is to add a comment for registration of collector to say that one should NOT override a registration (and should only be done for testing purposes). And then can you open an issue referencing this thread.

_Originally posted by @lumjjb in https://github.com/guacsec/guac/pull/1500#discussion_r1439800731_

**Comment by arorasoham9** [comment]
Could I get some more information on what is required here?
