### ISSUE TITLE
Increase golanglint CI timeout

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#163]
Golang lint CI seems to timeout sometimes.. We should increase the timeout threshold!

https://github.com/guacsec/guac/blob/main/.github/workflows/ci.yaml#L90

**Comment by krishnaindani** [comment]
hey, could I work on this?

**Comment by lumjjb** [comment]
Go for it!!! 😄 I'll assign you!

**Comment by krishnaindani** [comment]
thank you, I will start working on this

**Comment by Siddhant-K-code** [comment]
Currently `golanglint` usually takes ~[`57000ms` ](https://github.com/guacsec/guac/actions/runs/3301617490/jobs/5447291798#step:6:29). For the safer side, we can set the timeout limit to `60000ms`. This could be an easy quick fix.

Proposed solution:

- Introducing a new file `.golangci.yaml` in root of the repository.
- file content:

```yml
run:
  timeout: 2m
```
- We do not need to define this file in [our workflow](https://github.com/guacsec/guac/blob/a61422c7892b7f231e5e42b3d398fc47bf78df93/.github/workflows/ci.yaml#L90-L91). It will be configured automatically.

> **Note**: 2 minutes to be on the safer side. 


I can send out the PR.

**Comment by lumjjb** [comment]
Sounds good to me 2 minute seems like plenty of time!

**Comment by mihaimaruseac** [comment]
Fixed by #181

**Comment by Siddhant-K-code** [comment]
Thanks @mihaimaruseac for raising out the PR 🙌🏼

**Comment by mihaimaruseac** [comment]
It's @krishnaindani who did the work, thank you @krishnaindani
