### ISSUE TITLE
[bug] `DocumentITE6Generic` does not have a corresponding parser

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1633]
**Describe the bug**

`DocumentITE6Generic` document type is classified when the `payloadType` for DSSE is evaluated. This evaluation is wrong, and rather it should be using the `predicateType` as described here: https://github.com/in-toto/attestation/tree/main/spec/predicates

https://github.com/guacsec/guac/blob/main/pkg/handler/processor/dsse/dsse.go#L70C24-L85

We should also remove `DocumentITE6Generic` as it is not being used nor is there a parser associated with it.

**To Reproduce**
Create a DSSE with a SBOM payload

**Expected behavior**
Unpack of the DSSE with the proper document type that leads to the proper parser

**Screenshots**

**GUAC version**
main

**Additional context**

**Comment by pxp928** [comment]
Further discussion, the payload can just be the SPDX or CDX SBOM in the DSSE. It does not need to be a specific predicate as described here: https://github.com/in-toto/attestation/tree/main/spec/predicates

**Comment by kanchan-dhamane** [comment]
Thanks Parth.
