### ISSUE TITLE
[question] When can we expect a new release?

### ISSUE THREAD

**Issue by jens1o** [guacsec/guac#1636]
## Question

Unfortunately, when deploying with docker-compose, one must rely on having a recent release.

I've seen that there are plenty new features and enhancements in main since the last release in October.

Hence, is there a timespan for when we can expect a new minor release?

**Comment by pxp928** [comment]
Hey @jens1o thank you for the question, yes our goal is to get a new release out soon with updated documentation. 

We are also discussing a proper schedule for minor releases periodically so that there is less gap between each release.

**Comment by pxp928** [comment]
@jens1o v0.4.0 just got released!

**Comment by lumjjb** [comment]
I am going to work on a release information document, where we are looking towards monthly or bi-monthly releases. more to come!

**Comment by pxp928** [comment]
Releases happening on a regular cadence!
