### ISSUE TITLE
[bug] S3 collector fails to ingest

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1644]
**Describe the bug**
guacone collect s3 fail to ingest data from an S3 bucket. Running the following command:
```
guacone collect s3 --s3-bucket <bucket name> --s3-region us-west-2 --s3-mp sqs --s3-queues <queue name>
```
The command returns the following output:
```
{"level":"info","ts":1704712935.496344,"caller":"logging/logger.go:70","msg":"Logging at info level"}
{"level":"info","ts":1704712935.496462,"caller":"cli/init.go:67","msg":"Using config file: /Users/amisingh/Projects/guac/guac.yaml"}
{"level":"info","ts":1704712935.497071,"caller":"cmd/s3.go:141","msg":"completed ingestion"}
```
but nothing is ingested. 

Further action needs to be done to check what is causing this error. Also, need to determine if kafka and sqs are needed for the S3 collector to function as it adds a lot of complexity. 

**Expected behavior**
Successful ingestion from the S3 bucket

**GUAC version**
main

**Additional context**
Currently S3 collector is commented out from `guacone` until this is resolved for the new release: https://github.com/guacsec/guac/pull/1645

**Comment by dejanb** [comment]
@pxp928 Thanks for raising this ... Let me go through the collector and test, fix and document everything
