### ISSUE TITLE
[feature] Update the client side graphQL to with proper naming to match server side

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1663]
**Is your feature request related to a problem? Please describe.**
Currently, the [client side graphQL](https://github.com/guacsec/guac/tree/main/pkg/assembler/clients/operations) function naming are ambiguous. These should be updated to match the [server side](https://github.com/guacsec/guac/tree/main/pkg/assembler/graphql/schema)

Once complete, run `make generate` to update the generated code and fix any issues that arise from the renaming.
 
**Describe the solution you'd like**
For example, [mutation IsDependency](https://github.com/guacsec/guac/blob/main/pkg/assembler/clients/operations/isDependency.graphql#L20) should be renamed to `mutation IngestDependency`. This needs to be done for all the mutations and queries.

**Comment by arorasoham9** [comment]
I can take this
