### ISSUE TITLE
[bug] HTTP address of metrics endpoints clash 

### ISSUE THREAD

**Issue by mdeicas** [guacsec/guac#1676]
**Describe the bug**
Currently the deps.dev collector and guacgql attempt to start up an http server to serve the metrics endpoint, but they both use the same port (9091) by default, so whichever is started up second crashes. The port can be configured with a flag, but this should be able to work by default. 

**To Reproduce**
Nats is started up, because otherwise a failed connection to Nats may cause an error before the metrics server does. 

1.  `docker run -p 4222:4222 -p 8222:8222 docker.io/library/nats:2.9.17-alpine -m 8222 -js`
2. `./guacgql`
3. `./guaccollect deps_dev` 

The error received is: 
```
{"level":"fatal","ts":1706575359.2996292,"caller":"cmd/deps_dev.go:108","msg":"Error starting HTTP server: listen tcp :9091: bind: address already in use", "stacktrace": "..."}
```

**Expected behavior**
Different guac components should be able to start up successfully without requiring configuration of the port which to serve the metrics endpoint from. I also think that for guacgql, the metrics endpoint can be directly added to the existing http graphql server instead of serving the endpoint on a new server on a different port.  

**GUAC version**
`c3464f8034db5222e59de42c13f67056dc2a1ec6`.

**Comment by pxp928** [comment]
FYI @naveensrinivasan

**Comment by mdeicas** [comment]
I also think that we should we set the default for the `enable-prometheus` flag to false, to avoid having http servers running if they are not being used.

**Comment by arorasoham9** [comment]
I can take this

**Comment by arorasoham9** [comment]
Can we just change the default ports for either service?
`	set.Bool("enable-prometheus", true, "enable prometheus metrics")

	set.Int("prometheus-addr", 9091, "port to listen to on prometheus server")
`
