### ISSUE TITLE
[feature] "FindSoftware" implementation for KeyValue

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1706]
**Is your feature request related to a problem? Please describe.**
Currently [FindSoftware](https://github.com/guacsec/guac/blob/main/pkg/assembler/graphql/schema/search.graphql#L17-L36) has been implemented for the [arango backend](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/arangodb/search.go) and the [ENT backend](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/ent/backend/search.go) but not for the [Keyvalue backend](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/keyvalue/search.go).

This needs to be completed such that the demo can utilize this feature.

**Describe the solution you'd like**
Implementation on the keyvalue backend that does a "contains" search on `pkgName`, `sourceName` and `artifact` and return all that match.

**Additional context**
An example would look like the following (in graphQL playground):

```
query FindCurl {
  findSoftware(searchText: "curl") {
    __typename
    ... on Package {
      type
      namespaces {
        namespace
        names {
          name
        }
      }
    }
  }
}
```

This yields succinct results of just 27 relevant curl software - both packages and libraries, from debian, alpine, pycurl, rpm/amzn, etc. 

 	
```
{
  "data": {
    "findSoftware": [
      {
        "__typename": "Package",
        "type": "alpine",
        "namespaces": [
          {
            "namespace": "",
            "names": [
              {
                "name": "libcurl"
              }
            ]
          }
        ]
      },
      {
        "__typename": "Package",
        "type": "alpine",
        "namespaces": [
          {
            "namespace": "",
            "names": [
              {
                "name": "curl"
              }
            ]
          }
        ]
      },
     …TRUNCATED
      {
        "__typename": "Package",
        "type": "deb",
        "namespaces": [
          {
            "namespace": "ubuntu",
            "names": [
              {
                "name": "libcurl4-openssl-dev"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by nathannaveen** [comment]
I would like to work on this.
