### ISSUE TITLE
[feature] Add in missing collectors to guaccollect

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1721]
**Is your feature request related to a problem? Please describe.**
Add in the missing collectors to [guaccollect](https://github.com/guacsec/guac/tree/main/cmd/guaccollect/cmd). Currently, GCS, S3, and git are missing. This would allow them to be used via `guacingest` with pubsub and blob store.

The implementation for these will be very similar to [guaccollect files](https://github.com/guacsec/guac/blob/main/cmd/guaccollect/cmd/files.go).

GCS and S3 are implemented in [guacone](https://github.com/guacsec/guac/tree/main/cmd/guacone/cmd) so that can be used as a reference. 

NOTE:

The documentation (https://docs.guac.sh/) needs to be updated on how to properly set up and utilize `guaccollect`

**Comment by pxp928** [comment]
cc @kanchan-dhamane

**Comment by nathannaveen** [comment]
Could I work on this?

**Comment by pxp928** [comment]
The documentation (https://docs.guac.sh/) needs to be updated on how to properly set up and utilize `guaccollect`

**Comment by pxp928** [comment]
Closing this issue as the work is done. Adding documentation issue https://github.com/guacsec/guac-docs/issues/120
