### ISSUE TITLE
Handling cases where a collection's index is missing or renamed

### ISSUE THREAD

**Issue by semmet95** [guacsec/guac#1722]
**Describe the bug**
`isOccurrence` collection used to have an index named `byPkgIDArtIDJust` which was renamed to `byPkgIDArtIDOriginJust` in September 2023 under [this](https://github.com/guacsec/guac/commit/88dfb7ea1c9b4e2f023c082f152ef22138e832b0#diff-1aba4420a9017b9d486c0fab38a08b9eea2e9c22e2402039d7726f26b1ccf544L560) commit. The change also includes addition of the field `origin` to the index.

However, since guac [creates indices](https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/arangodb/backend.go#L141-L151) only if the `guac` graph doesn't already exist, the whole process of creating new/renamed indices is skipped when we already have a database and are not starting from scratch.

This issue is not just about creating new collection indices but also about managing the old ones. Should we delete all the existing indices that are not in our current map? Should we edit them? Or are there better options?

**To Reproduce**

1. Clone the repo and switch to the [80eab75](https://github.com/guacsec/guac/tree/80eab75cc78ff433a5cc3cf6b4e8d873391f8bd5) commit state
2. Run `make container` to create the `local-organic-guac` image
3. Switch to the `main` branch
4. Update the `‎guac-graphql‎` container in [arango.yaml](https://github.com/guacsec/guac/blob/main/container_files/arango.yaml) file to refer to the image created in step#2
5. In Arango DB UI check that the index `byPkgIDArtIDJust` is created
6. Ingest a provenance and verify the corresponding entry shows up in the `isOccurrence` collection
7. Update the `‎guac-graphql‎` container image to `local-organic-guac` image built out of the `main` branch
8. Check the indices of the `isOccurrence` collection

**Expected behavior**
`isOccurrence` collection should have only `byPkgIDArtIDOriginJust` index

**Ingested document(s)**
Any sample slsa provenance

Can you share the documents that are used to reproduce the ingestion errors or showcase the data quality issues.
No

**Comment by pxp928** [comment]
@semmet95, I can do some testing to see but until we reach a v1.0 for GUAC, we should be deleting old (unused) indexes manually (if arango is persistent). Once we have determined the proper indexes needed, we should not need to change them for the particular collection. 

As for adding/updating indexes, it should be fairly straightforward via edit them if `guac graph` exists within arango. I will take a look and provide a solution or steps to remediation.
