### ISSUE TITLE
Attach HasSboms to Artifacts instead of Packages when possible

### ISSUE THREAD

**Issue by mdeicas** [guacsec/guac#1736]
When a digest is available for the subject of an SBOM, the `HasSbom` node should be attached to an `Artifact` corresponding to that digest, and then an `IsOccurrence` should link the `Artifact` to a `Package`. 

@pxp928 identified a few more places where code changes are needed:
- update the Vuln CLI to take in hash to search for hasSBOM
- Update the patch planning CLI to use hasSBOM dependencies and not direct isDependency when calculating patch plan

**Comment by pxp928** [comment]
in my fork I started some of this work by pulling out the digest from CDX SBOM and creating an `IsOccurrence` from the top level package to the artifact: https://github.com/guacsec/guac/compare/main...pxp928:artifact-ff:issue-1734
