### ISSUE TITLE
[bug] Post \"http://localhost:8080/query\": read tcp [::1]:62501->[::1]:8080: read: connection reset by peer

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#1769]
**Describe the bug**
When running `go run ./cmd/guacone query vuln "urn:uuid:825c6001-17ba-4718-bb41-c1f8b66fdff0"`, this causes multiple connection reset errors to occur.

```
{"level":"error","ts":1710284706.855319,"caller":"cmd/vulnerability.go:439","msg":"error querying neighbor for vulnerability: Post \"http://localhost:8080/query\": read tcp [::1]:62501->[::1]:8080: read: connection reset by peer",
```

When checking the query manually via the graphQL playground, this issue does not occur.

Based on this, it leads me to believe that the issue maybe on the the client-side generated code?

https://github.com/guacsec/guac/tree/main/pkg/assembler/clients

Need to investigate why this error occurs but sometimes it does not.

**To Reproduce**
- `go run ./cmd/guacgql --gql-debug`
- `go run ./cmd/guacone collect files <path to file>`
- ingest 
[vuln-syft-cdx.json](https://github.com/guacsec/guac/files/14579858/vuln-syft-cdx.json)

- `go run ./cmd/guacone certifier osv`
-  `go run ./cmd/guacone query vuln "urn:uuid:825c6001-17ba-4718-bb41-c1f8b66fdff0"`

You should see the connection reset errors

**Expected behavior**
Not receive any connection reset errors

**GUAC version**
main branch

**Comment by pxp928** [comment]
@mihaimaruseac Any ideas what could be causing this? I was looking at `genqlient` to see if there was an issue in the generated code?

**Comment by pxp928** [comment]
[vuln-syft-cdx.json](https://github.com/guacsec/guac/files/14579863/vuln-syft-cdx.json)

**Comment by pxp928** [comment]
[vuln-syft-cdx.json](https://github.com/guacsec/guac/files/14579886/vuln-syft-cdx.json)

**Comment by pxp928** [comment]
Removing https://github.com/guacsec/guac/blob/main/cmd/guacone/cmd/vulnerability.go#L431-L449 does not cause the error to occur. Need to investigate more.

**Comment by lumjjb** [comment]
did you figure out what was causing this? or was this a environmental issue? if we cant reproduce, perhaps we can close for now.

**Comment by mihaimaruseac** [comment]
It's the server getting overloaded :(

**Comment by pxp928** [comment]
yeah the server is being overloaded which caused this error.
