### ISSUE TITLE
[bug] Goreleaser deprecation warnings in local build

### ISSUE THREAD

**Issue by huggingpixels** [guacsec/guac#1813]
**Describe the bug**
When building container using the makefile described by the documentation, two deprecation warnings are displayed by goreleaser. Updating the flags to the currently supported syntax does not change the behaviour but cleans up the output.

**To Reproduce**

1. Run `make build_local_container` 
2. See deprecation warnings in the logs before the script loads environment variables

**Expected behavior**
Do not have deprecation warnings in the logs.
Skip signing and sbom steps as with the deprecated tags.

**Screenshots**
`DEPRECATED: --skip-sign was deprecated in favor of --skip=sign, check https://goreleaser.com/deprecations#-skip for more details`
`DEPRECATED: --skip-sbom was deprecated in favor of --skip=sbom, check https://goreleaser.com/deprecations#-skip for more details`

**GUAC version**
Does not effect a certain version, only release tooling.

**Comment by lumjjb** [comment]
Thanks @huggingpixels for flagging this! and for the PR!
