### ISSUE TITLE
[feature] Switch out archived github.com/golang/mock repo with maintained fork github.com/uber-go/mock

### ISSUE THREAD

**Issue by nchelluri** [guacsec/guac#1838]
**Is your feature request related to a problem? Please describe.**
In https://github.com/guacsec/guac/blob/3dba718a5c66d0878af8bc90c2a82022a29bfc0f/go.mod#L293 you can see that GUAC currently makes use of [github.com/golang/mock](https://github.com/golang/mock). But if you view the README for that repo, you will see that it has been archived and is unmaintained; [it says](https://github.com/golang/mock/blob/main/README.md?plain=1#L3-L4):

> **Update, June 2023**: _This repo and tool are no longer maintained.
> Please see [go.uber.org/mock](https://github.com/uber/mock) for a maintained fork instead._

The purpose of this ticket is to switch to the [Uber fork](https://github.com/uber-go/mock).

**Describe the solution you'd like**
I think that to switch from the archived package to the new Uber package you would likely have to update all instances of `github.com/golang/mock` in this repo with `github.com/uber-go/mock`. I am hoping that would handle it.

**Comment by rakshitgondwal** [comment]
Hey @nchelluri! I'd like to work on this.

**Comment by pxp928** [comment]
Thanks @rakshitgondwal I assigned you this issue. Once all the changes are complete you may need to regenerate the mocked code. This is usually done in the repo via `make generate`.  Let us know if you run into any issues or have questions.

**Comment by rakshitgondwal** [comment]
Sure, Thanks @pxp928.
