### ISSUE TITLE
[rolling] Community contribution ladder climbs 04/30

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#1885]
Official vote documentation for the following folks who've done great contributions to GUAC! 

(some of these were agreed upon/announced before, so a bit of a retroactive)

- Dejan Bosanac (https://github.com/dejanb) +reviewer:ingestion 
  - SPDX and CDX parser additions [[1](https://github.com/guacsec/guac/pull/707),[2](https://github.com/guacsec/guac/pull/603),[3](https://github.com/guacsec/guac/pull/1437),[4](https://github.com/guacsec/guac/pull/655)]
  - Fix: s3 collector [[1](https://github.com/guacsec/guac/pull/1658)]
  - TLS for servers [[1](https://github.com/guacsec/guac/pull/1390),[2](https://github.com/guacsec/guac/pulls?q=is%3Apr+author%3Adejanb+is%3Aclosed+#:~:text=Support%20TLS%20for%20graphql%20server)]

- Marco Rizzi (https://github.com/mrizzi), +owner:backend
  - Foundational in creation and development of the Ent backend! (https://github.com/guacsec/guac/pulls?q=is%3Apr+author%3Amrizzi+is%3Aclosed)

- Marco Deicas (https://github.com/mdeicas), +reviewer: GraphQL
  - Contributed to the creation of the REST API for transitive queries, including pagination [[1](https://github.com/guacsec/guac/pull/1665), [2](https://github.com/guacsec/guac/pull/1867), [3](https://github.com/guacsec/guac/pull/1720)]

**Comment by lumjjb** [comment]
Maintainer votes: @jeffmendoza @pxp928 @mlieberman85 @SantiagoTorres @mihaimaruseac

**Comment by lumjjb** [comment]
+1 on all from me

**Comment by pxp928** [comment]
+1 for all!

**Comment by mihaimaruseac** [comment]
+1 for all!

**Comment by jeffmendoza** [comment]
+1 To all 3. Thanks!

**Comment by mlieberman85** [comment]
+1 for Dejan, Marco, and Marco

**Comment by lumjjb** [comment]
changes reflected in CONTRIBUTING.md
