### ISSUE TITLE
OpenSSF WG alignment?

### ISSUE THREAD

**Issue by sevansdell** [guacsec/guac#2055]
Hi - I'm looking at the GUAC github, and it's not clear to me which WG in OpenSSF this project is or what the lifecycle stage its' in. I've been sharing the project with some team-mates internally, and want for them to see the association with OSSF and which WG the project aligns. Thanks!

**Comment by mlieberman85** [comment]
Hi @sevansdell I'll update the README to include that info. For now the info is in the TAC Readme: https://github.com/ossf/tac

**Comment by funnelfiasco** [comment]
Hi @sevansdell, Mike beat me to updating the readme, but I'll also make sure it's clear on the [website](https://guac.sh). Apart from the website and this repo's readme, are there other places that you would expect to find this?
