### ISSUE TITLE
[ingestion/clearlydefined] clearlydefined fails to run when the osv certifier has already run

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#2077]
**Describe the bug**
 clearlydefined fails to run when the osv certifier has already run. This occurs because root package query checks if certifyVulns are already collected and skips the package. This should not happen when the clearly defined certifier is run. 
 
 Question is, should this check be removed? As we want the certifiers to run on OSV and clearlydefined on various intervals, re-adding new vulns or licenses as they are found. The check was only added to prevent the certifier from running again manually and adding duplicate vuln nodes. This, in the long term, is actually what we want to happen in GUAC as we know that the information is up-to-date.

 
**To Reproduce**

1. `go run ./cmd/guacgql --gql-debug --gql-backend=ent`
2. `go run ./cmd/guacone collect files spdx_vuln.json`
3. `go run ./cmd/guacone certifier osv`
4. `go run ./cmd/guacone certifier cd`

You will notice that it completes without adding any licenses.

**Expected behavior**
Add all the license information based on clearly defined.

**GUAC version**
v0.8.0

**Comment by funnelfiasco** [comment]
Removing the check seems like the right call. If it's preventing certifiers from running, that defeats the purposes of certifiers.

**Comment by pxp928** [comment]
> Removing the check seems like the right call. If it's preventing certifiers from running, that defeats the purposes of certifiers.

To add more context and looking back at the code, we need to keep the checks to determine when the last scan occurs so that the certifier can determine if a re-scan needs to happen again (based on the interval set by the user).

I need to think of a better approach for how we want to handle this.

**Comment by pxp928** [comment]
After further thought, we can remove `daysSinceLastScan` as it is redundant with the certifier interval. This will also reduce the load on the DB as neighbors will not need to be called. Plus with the addition of:
```
# query vulnerability during ingestion
add-vuln-on-ingest: true

# query licenses during ingestion
add-license-on-ingest: true
```

This will keep the license and vulns up to date.
