### ISSUE TITLE
Utilizing wealth of Deps.dev information

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#214]
[Deps.dev](https://deps.dev/) has a lot of existing data crawled from open source packages. We'd ideally be able to utilize the information available there to perform analysis and aggregation from.

There are two modes that a large data set like `Deps.dev` can be used. 
- One is through a standard collector, where it emits documents about what it knows and that gets ingested into GUAC, taken from the bigquery table
- Another use case which may be useful is as a data augmenter (similar to certifiers). Based on information in GUAC, it emits documents which augment the particular data sets in GUAC

Additional evaluation needs to be done to determine the best way to go forward with using Deps.dev information.

**Comment by lumjjb** [comment]
We can do something like the OSV certifier where we get a bunch of PURLs and query the deps.dev data set and put information in! https://github.com/guacsec/guac/tree/main/pkg/certifier/osv, should be a pretty straightforward exercise in terms of parsing PURLs and querying them through the deps.dev dataset https://deps.dev/data

**Comment by naveensrinivasan** [comment]
@pxp928  Are you working on this? If not, I'd like to take it on.

**Comment by pxp928** [comment]
Hey @naveensrinivasan, yea I have already stared work on this. PR coming later next week. Would you be interested in working on the [scorecard collector](https://github.com/guacsec/guac/issues/249)?
