### ISSUE TITLE
[feature] Add ClearlyDefined to e2e test

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#2142]
**Is your feature request related to a problem? Please describe.**

Currently Clearly Defined is not being tested in [e2e](https://github.com/guacsec/guac/blob/main/internal/testing/e2e/e2e). This needs to be added.

**Describe the solution you'd like**

Add `--add-license-on-ingest` https://github.com/guacsec/guac/blob/main/internal/testing/e2e/e2e#L100
and also add a certifyLegal query to check that the license exists.

**Comment by robert-cronin** [comment]
I would like to try and help with this one!
