### ISSUE TITLE
[API] Design and implement a basic GraphQL GUAC API and data model for generic queries

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#216]
Create a basic GraphQL interface for GUAC. This should be an initial design and implementation of how users can interact with GUAC. This issue will provide a way to reason about fundamental API principles in GUAC as well as provide context for future API design decisions.

**Comment by lukehinds** [comment]
Has there been any decision on the client lib (e.g. gqlgen, graphql-go)?

**Comment by mihaimaruseac** [comment]
Most likely `gqlgen`. I don't feel the same level of control on `graphql-go`, but giving it one more try before final decision

**Comment by mihaimaruseac** [comment]
Wrote an initial design doc for this at https://docs.google.com/document/d/1yZ3-ZcfnRDWgw9uZlPuLmIHS9pNMr3DO_AEbHsDXmN8/edit?usp=sharing

It touches several other issues in the repo.

While working on this, will mention the relevant issues in the commits/PRs

**Comment by lumjjb** [comment]
Yes!!! The architecture of it will be similar to what's outlined in @mihaimaruseac 's doc, but we're still in the process of solidifying what the edge and node types will be! We're having some discussions soon and will have a RFC when we put the draft together! Should hear a bit more soon!

**Comment by lumjjb** [comment]
ontology definitions are expressed here: https://docs.google.com/document/d/1vEMtJnXrQ0MGnierLE-7pXAcw2j563qXh_PyHpeaEzA/edit#heading=h.m6wnhglv3jce

**Comment by abuishgair** [comment]
the ontology document can be found here: 
https://docs.google.com/document/d/1sPC-YKZyUjtPdI5-B4uOUX6QomYyc6JuHn3EAdLJ9Tg/edit?usp=sharing

**Comment by mihaimaruseac** [comment]
This is now fully implemented with in-memory backend
