### ISSUE TITLE
[API] Design and develop a GUAC API to query vulnerability information in a useful way for policy making and insights (e.g. What artifacts/packages depend on a particular library (e.g. log4j))

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#223]
Design and develop a GUAC API to query vulnerability information in a useful way for policy making and insights (e.g. What artifacts/packages depend on a particular library (e.g. log4j))

Depends on https://github.com/guacsec/guac/issues/222, https://github.com/guacsec/guac/issues/216

**Comment by pxp928** [comment]
This is completed via the graphQL API and [query vulnerability CLI](https://github.com/guacsec/guac/blob/main/cmd/guacone/cmd/vulnerability.go)
