### ISSUE TITLE
[bug] ClearlyDefinedTests are flaky

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#2290]
**Describe the bug**
Clearly defined tests are flaky

**To Reproduce**

See failing CIs: https://github.com/guacsec/guac/actions/runs/11797715031/job/32862288131

**Expected behavior**

Tests should not flake

**Screenshots**

**GUAC version**
NA

**Additional context**

**Comment by pxp928** [comment]
[TestPurlsLicenseScan](https://github.com/guacsec/guac/blob/main/pkg/ingestor/parser/common/scanner/scanner_test.go#L343) is also being skipped as CD fails to respond in time.
