### ISSUE TITLE
[bug] Broken workflow permissions

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/guac#2315]
The workflow permission changes I made in #2276 probably include some overly-restricted permissions that will cause the workflow to fail. guac-visualizer has similar changes, so once we get those ironed out, I'll fix them here as well.

**Comment by funnelfiasco** [comment]
Reopening because, looking at the [release workflow history](https://github.com/guacsec/guac/actions/workflows/release.yaml), it has failed with "Startup failure" since #2276 was merged. I can't see any indication why.

**Comment by pxp928** [comment]
Error reported:
```
The workflow is not valid. .github/workflows/release.yaml (Line: 174, Col: 3): Error calling workflow 'slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0'. The workflow is requesting 'contents: read', but is only allowed 'contents: none'. .github/workflows/release.yaml (Line: 174, Col: 3): Error calling workflow 'slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0'. The nested job 'detect-env' is requesting 'id-token: write', but is only allowed 'id-token: none'.
```

**Comment by funnelfiasco** [comment]
#2341 should fix this
