### ISSUE TITLE
[bug] guacrest binary crashing

### ISSUE THREAD

**Issue by semmet95** [guacsec/guac#2330]
**Describe the bug**
`guacrest` binary is crashing on running any command.

**To Reproduce**

1. Build the binaries using `make build_bins`
2. Run any command with the `guacrest` binary
```
./dist/guacrest_darwin_arm64/guacrest-darwin-arm64 --version
```
3. See error
```
failed to setup flags: Flag not found : db-driver% 
```

**Expected behavior**
Version of the binary printed as the output.

**Screenshots**
<img width="474" alt="image" src="https://github.com/user-attachments/assets/5355233c-6254-4197-9144-4c7e559de39b">

**GUAC version**
`main` branch

**Additional context**
It seems `guacrest` [requires](https://github.com/guacsec/guac/blob/main/cmd/guacrest/cmd/root.go#L84-L85) `db-driver` and `db-address` flags but they were removed from the store in [this PR](https://github.com/guacsec/guac/pull/2247/files#diff-44d573cf29eee810e1163bbd743b22eafca57fb85946ab7e35507cc8be8d3b95L84-L85).

**Comment by robert-cronin** [comment]
Great catch! Thank you @semmet95 for catching that! I missed this use case when doing that PR. I think this can be solved by importing the ent backend as it seems rest is using that backend directly: 
https://github.com/guacsec/guac/blob/main/pkg/assembler/backends/ent/backend/backend.go#L56

I'll add a PR to fix this issue!
