### ISSUE TITLE
task: create make check and make binaries

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#24]
Create a makefile with make check to check golang compilation, testing and linting

**Comment by nadgowdas** [comment]
I can take a crack at it, will create a PR

**Comment by mihaimaruseac** [comment]
For CI, see #14, should have a PR today/tomorrow but should be orthogonal to creating `Makefile`, etc.

**Comment by lumjjb** [comment]
Addressed by https://github.com/guacsec/guac/pull/25
