### ISSUE TITLE
Figure out how to handle CycloneDX components that don't come with PURLs.

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#240]
While working with some CDX SBOMs, we were faced with some entries where PURLs were not available (ref: https://github.com/guacsec/guac/issues/236). 

Additional discussion is needed to ensure that we are able to handle these cases in a way that is valid for our use cases.

**Comment by pxp928** [comment]
This is handled by the current implementation of the [CDX parser](https://github.com/guacsec/guac/blob/main/pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go).
