### ISSUE TITLE
Testing requires more granular graphDB queries

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#242]
While writing some tests, having the ability to have more granular database queries is very helpful! However, the issue it brings about is that this muddles the abstraction of the graph DB being transparent (vs having graphQL queries for each thing).

The current approach is to continue with direct database queries for tests for now, and if/when the a new DB gets added to abstract these queries into debuggable graphQL interfaces.

**Comment by pxp928** [comment]
Add missing unit tests to `graphdb.go` for `StoreGraph` and `Subscribe`

**Comment by pxp928** [comment]
This is being reworked to create unit tests for the various backend resolvers.

**Comment by pxp928** [comment]
Added unit tests to the in-memory backend resolvers (that can be used for conformance tests for others). @mihaimaruseac Close this issue as completed or is there more associated with this issue?

**Comment by mihaimaruseac** [comment]
I think this is done. At the time we had the ability to get an entire subgraph out of neo4j and then the test needed to parse it, but now with graphql we can get all data we need.
