### ISSUE TITLE
GUAC Beta user service for SLSA/SBOM query service (CHIP)

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#250]
A service to ingest SLSA/SBOM from the user and return results by querying the GraphQL API.

Include a set of services to help users (through a web interface), interact with GUAC. 

Tracking within the repo, but this will likely be a "Chip" of GUAC.

### The GUAC Web UI

<img width="1180" alt="Screenshot 2023-01-30 at 11 44 53 AM" src="https://user-images.githubusercontent.com/3060102/215540287-dd37086a-92f0-405b-835f-e253ba576747.png">

### The GUAC results page with insights and navigable graph

<img width="1173" alt="Screenshot 2023-01-30 at 11 45 01 AM" src="https://user-images.githubusercontent.com/3060102/215540334-a8cc1405-cd82-4e62-a19f-e542ac01b759.png">

**Comment by pxp928** [comment]
UI is able to query for package and show a graph output. Various CLI and python scripts have been created to interact with the grapQL data.
