### ISSUE TITLE
How to ingest self signed dsse document into guac? (implementing a CA verifier)

### ISSUE THREAD

**Issue by saipraveen88** [guacsec/guac#304]
Use case: Ingest a self signed dsse envelope, which generates a knowledge graph of an artifact.

Today, looks like guac only [ingests](https://github.com/guacsec/guac/blob/main/SETUP.md) dsse documents signed by Sigstore. Any self signed dsse documents are failing to ingest at verify signature step, as guac currently supports "sigstore" as the only [registered provider](https://github.com/guacsec/guac/blob/main/pkg/ingestor/verifier/verifier.go#L73). 

We here at [Guidewire Software](https://www.guidewire.com/) are currently self signing the in-toto statement while generating the signed [dsse document](https://github.com/in-toto/attestation/blob/main/spec/README.md#envelope) for our CI build stages. Can you please suggest on how can we ingest a self signed dsse document into the guac?

**Comment by lumjjb** [comment]
Thanks for opening this up @saipraveen88 ! Yes, this is something that should be included. It looks like this warrants the creation of a new verifier and adding it to the list of verifiers to go through for validation. We'll use this issue to track this work, will rename to reflect task.

What is the format of inputs you are looking to use? Is your authority an x509 cert or GPG key? In running the ingestor would the addition of a public key be sufficient like `guacone --CA=ca.pem ...`? 

Also - we have a [design document](https://docs.google.com/document/d/1BUEi7q2i-KXlAhsh1adYvL1fkWN-q8FrgLyEre7c5kg/edit?resourcekey=0-02sC5-9IbTfwJckze_CDQw#heading=h.h9kfextfhlqn) which came from #217 that may contain a relevant section ["Trust Policy"](https://docs.google.com/document/d/1BUEi7q2i-KXlAhsh1adYvL1fkWN-q8FrgLyEre7c5kg/edit?resourcekey=0-02sC5-9IbTfwJckze_CDQw#heading=h.h9kfextfhlqn) that may be of interest to you - and we'd like some feedback on that. 

(side note upon revisiting that code i realized that we forgot to register the sigstore verifier which led to a failure, created #307).

**Comment by lumjjb** [comment]
Would it be helpful for your usage if in the meantime we could provide a quick interim `--no-verify` flag which will skip verification in general, so you can at least ingest the DSSEs and use them if you are only gathering from trusted sources?

**Comment by pxp928** [comment]
@saipraveen88 We have a maintainer planning meeting today and I will bring this up as a priority to fix/add.

**Comment by pxp928** [comment]
@saipraveen88 PR https://github.com/guacsec/guac/pull/311 will be merged soon. Let me know if that solves your issue.

**Comment by pxp928** [comment]
Once caveat currently is that the keyID needs to be the hash of the public key:
```
{
  "payload": "<Base64(SERIALIZED_BODY)>",
  "payloadType": "<PAYLOAD_TYPE>",
  "signatures": [{
    "keyid": "<KEYID>",
    "sig": "<Base64(SIGNATURE)>"
  }]
}
```
We are looking to see if that needs to be changed in sigstore or other upstream places.

**Comment by pxp928** [comment]
Hey @saipraveen88, did this work for you? Let me know and we can close out this issue or if you need something else.

**Comment by sasi-07** [comment]
Hey @pxp928, we tested out the change by successfully ingesting a self-signed document by passing valid `--verifier-keyID` &  valid `--verifier-keyPath` as arguments to the guacone cli. 
However the ingestion was successful even when we passed a valid `--verifier-keyID` and invalid `--verifier-keyPath`.

**Comment by pxp928** [comment]
Hello @sasi-07, thank you for the feedback. Could you provide more details on your second use case where it was a valid `--verifier-keyID` and invalid `--verifier-keyPath`? Meaning the keyID was the hash of the valid public key but the public key you passed in via `--verifier-keyPath` was a different key?

**Comment by sasi-07** [comment]
Right, we passed the hash of the valid public key as KeyID and path to a different public key in `--verifier-keyPath`.

**Comment by pxp928** [comment]
@sasi-07 what about the invalid keypath? Identity nodes created?

**Comment by sasi-07** [comment]
@pxp928 Yes even for invalid keypath identity nodes were created.

**Comment by pxp928** [comment]
@sasi-07 seems like I cannot replicate this. Can you send me what you are inputting for the keyID and is your key a `pem` file?

**Comment by pxp928** [comment]
@sasi-07 found the issue. Now it will not create identity nodes for invalid keys.

**Comment by pxp928** [comment]
@saipraveen88 @sasi-07 good to close this issue?

**Comment by pxp928** [comment]
Closing this issue. Please let us know if there are any more issues and we can open a new issue.
