### ISSUE TITLE
Polling tests that use context with timeouts are brittle

### ISSUE THREAD

**Issue by mlieberman85** [guacsec/guac#319]
See: https://github.com/guacsec/guac/actions/runs/3905153627/attempts/1 and https://github.com/guacsec/guac/actions/runs/3905153627/attempts/2

I have seen some of these tests intermittently fail.

**Comment by lumjjb** [comment]
hmm should we just up the timer for now?

**Comment by pxp928** [comment]
@mlieberman85 Is this completed?

**Comment by pxp928** [comment]
Completed.
