### ISSUE TITLE
Is There a Difference Between Structs

### ISSUE THREAD

**Issue by nathannaveen** [guacsec/guac#322]
Hi, I was trying to test `pkg/certifier/osv/internal/osv_query/osv_query.go` and saw that there are the structs, `BatchedResponse` and `HydratedBatchedResponse`:

https://github.com/guacsec/guac/blob/3dd89315ddecf795fef1c5374cea77246d37aaf2/pkg/certifier/osv/internal/osv_query/osv_query.go#L80-L88

`HydratedBatchedResponse` only has ``Results []Response `json:"results"` `` in it, and `BatchedResponse` has ``Results []MinimalResponse `json:"results"` `` in it.

`Response` is:

``` go
type Response struct {
	Vulns []osv.Entry `json:"vulns"`
}
```

And `MinimalResponse` is:

``` go
type MinimalResponse struct {
	Vulns []osv.Entry `json:"vulns"`
}
```

So what makes `HydratedBatchedResponse` and `BatchedResponse` different, is there a reason they are two different structs?

**Comment by nathannaveen** [comment]
cc @pxp928, 👀

**Comment by pxp928** [comment]
@nathannaveen This file was copied over (and slightly modified) from the upstream project (now OSV Scanner). I did create another issue #323 to track that we eventually remove this from GUAC. Feel free to remove the redundant structs but overall the whole file will be removed in the near future once I speak with the OSV Scanner maintainers.
