### ISSUE TITLE
Certifier - OSV Scanner API for batch querying

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#323]
Currently, the OSV Scanner querying API is copied as an internal file. Working with upstream maintainers to determine a path forward to remove this [file](https://github.com/guacsec/guac/blob/main/pkg/certifier/osv/internal/osv_query/osv_query.go).

Continuation from PR comment:
https://github.com/guacsec/guac/pull/245#discussion_r1047996505

cc @oliverchang

**Comment by pxp928** [comment]
Currently, OSV Scanner does not allow for a direct query for a package based on a purl. See: https://github.com/google/osv-scanner/blob/main/pkg/osvscanner/osvscanner.go#L261. Determine if there is an alternative method or if this can be added to upstream OSV scanner.

**Comment by pxp928** [comment]
FYI @lumjjb

**Comment by oliverchang** [comment]
Currently our actual OSV querying code is in an internal package: https://github.com/google/osv-scanner/blob/main/internal/osv/osv.go

@another-rex would it make sense to make some of these public so other tools can call the OSV API through our client?

**Comment by another-rex** [comment]
That can work, we can put it under v1 folder under pkgs so that it's public and if there are any breaking changes it easy to update.

**Comment by pxp928** [comment]
Awesome thanks @another-rex!

**Comment by another-rex** [comment]
This is now merged: https://github.com/google/osv-scanner/pull/167, so the library should now be public:
> "github.com/google/osv-scanner/pkg/osv"

**Comment by pxp928** [comment]
Thanks, @another-rex and @oliverchang!
