### ISSUE TITLE
community : Two approvals for PR

### ISSUE THREAD

**Issue by naveensrinivasan** [guacsec/guac#339]
I understand the importance of having more than one approval for significant changes, but I'm concerned that having `2` approvals for every PR will slow down the project and add a burden on the maintainers. Is there a specific reason why `2` approvals are needed?

**Comment by mlieberman85** [comment]
It follows good security best practices. Given that this tool is intended to be one heavily involved in security we think it's a reasonable tradeoff.

e.g.: CNCF Supply Chain Best Practices - https://github.com/cncf/tag-security/blob/main/supply-chain-security/supply-chain-security-paper/CNCF_SSCP_v1.pdf See: "Enforce an independent four-eyes principle"

SLSA v0.1 requirements - https://slsa.dev/spec/v0.1/requirements#two-person-reviewed

**Comment by naveensrinivasan** [comment]
I have a different opinion. However, I respect your decision.
