### ISSUE TITLE
task: [processor] create SLSA DocumentTypeGuesser 

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#34]
As part of https://github.com/guacsec/guac/issues/26, we want to be able to create guessers to identify what format type a document is (using the guesser interface defined in https://github.com/guacsec/guac/tree/main/pkg/handler/processor/guesser). Based on the foundations laid in https://github.com/guacsec/guac/pull/27 .

This issue is to create SLSA document guesser.

**Comment by cpendery** [comment]
@lumjjb would you assign me to this?

**Comment by lumjjb** [comment]
done! Thanks!

**Comment by lumjjb** [comment]
it may be possible to implement 1 guesser to kill 2 birds with one stone with https://github.com/guacsec/guac/issues/35

Since it's going to be parsing the intoto predicate the only difference is checking the predicate type!
