### ISSUE TITLE
Use the wrapcheck linter

### ISSUE THREAD

**Issue by nathannaveen** [guacsec/guac#371]
Currently, a lot of errors that are returned are just returning the error and not giving any description to what the error is when debugging (ie. `return err`). A solution to this is to use the golang linter https://github.com/tomarrell/wrapcheck to write the errors using `fmt.Errorf()`.

**Comment by nathannaveen** [comment]
I will work on this.

**Comment by lumjjb** [comment]
>Wrapcheck is also available as part of the golangci-lint meta linter. Docs and usage instructions are available [here](https://github.com/golangci/golangci-lint). When used with golangci-lint, configuration is integrated with the .golangci.yaml file.

it looks like the repo says the wrapcheck is available also in golangci-lint, can we use that since we already have it.

**Comment by nathannaveen** [comment]
> > Wrapcheck is also available as part of the golangci-lint meta linter. Docs and usage instructions are available [here](https://github.com/golangci/golangci-lint). When used with golangci-lint, configuration is integrated with the .golangci.yaml file.
> 
> it looks like the repo says the wrapcheck is available also in golangci-lint, can we use that since we already have it?

Thanks, I have taken care of it.
