### ISSUE TITLE
New package for nodes.go

### ISSUE THREAD

**Issue by nathannaveen** [guacsec/guac#376]
In my opinion, [`pkg/assembler/nodes.go`](https://github.com/guacsec/guac/blob/main/pkg/assembler/nodes.go) should be split up into multiple files, and all those files should be in a separate package.

For example, we could have a package called `nodes` in `pkg/assembler`, and `nodes` should have the files, `artifactnode.go`, `packagenode.go`, `identitynode.go`, and so on, inside it.

**Comment by nathannaveen** [comment]
On second thought, splitting up `nodes.go` into multiple files without the package should be a good idea whether or not it is put into a different package.

**Comment by mihaimaruseac** [comment]
I would say don't focus on this package given that it will be obsolete soon by [the GraphQL assembler work](https://docs.google.com/document/d/1yZ3-ZcfnRDWgw9uZlPuLmIHS9pNMr3DO_AEbHsDXmN8/edit)

**Comment by pxp928** [comment]
Closing this issue as its no longer relevant with the changes made with graphQL
