### ISSUE TITLE
 Consider reducing buffer size in certifier package

### ISSUE THREAD

**Issue by naveensrinivasan** [guacsec/guac#381]
I was reviewing the code in the certifier package and noticed that the buffered channel used in the certify function has a size of `1000`. However, as stated in the article "The Behavior of Channels" by Ardan Labs (https://www.ardanlabs.com/blog/2017/10/the-behavior-of-channels.html), `A Buffered channel of size >1 gives you No Guarantee that a signal being sent has been received.
Because the Send of the signal Happens Before the Receive of the signal completes`.

In the context of the system, reliability should be a higher priority than high performance. Therefore, I suggest considering reducing the buffer size to ensure that signals are being received and processed correctly. This could potentially prevent any issues that may arise due to missed signals.

https://github.com/guacsec/guac/blob/478e52c4fbc201949904fa5591bb6e2d8ea631e4/pkg/certifier/certify/certify.go#L30

**Comment by lumjjb** [comment]
Having a buffer channel of size >1 only let's you continue the thread, it should not assume that the signal has been received. This should be handled by the program, and should not be an issue. Asynchronous concurrency model should be assumed so the code shouldn't rely on this assertion, and in other cases of failure, it is probably (at least in our case), not a situation where we can gracefully recover from and therefore would be a panic. I believe this shouldn't be an issue for that code usage.

**Comment by naveensrinivasan** [comment]
> Having a buffer channel of size >1 only let's you continue the thread, it should not assume that the signal has been received. This should be handled by the program, and should not be an issue. Asynchronous concurrency model should be assumed so the code shouldn't rely on this assertion, and in other cases of failure, it is probably (at least in our case), not a situation where we can gracefully recover from and therefore would be a panic. I believe this shouldn't be an issue for that code usage.

The current design does not provide assurance that all messages sent to the API will be processed, as the process could fail after processing only a portion of the requests. To address this, what measures are taken to ensure that consumers are aware of which messages have been processed and which ones have not?

**Comment by lumjjb** [comment]
that would be handled by the emit, so probably this concern would be better targeted towards the [emitters](https://github.com/guacsec/guac/tree/cf8ab736b5f895af4e86a570fd9d29a6a51dc15a/pkg/emitter), as they handle the interaction with external systems

**Comment by pxp928** [comment]
The emitter uses NATS which has been configured to use the `workQueuePolicy` which means:
"WorkQueuePolicy specifies that when the first worker or subscriber acknowledges the message it can be removed from the queue". So messages will remain in the queue.

**Comment by naveensrinivasan** [comment]
> that would be handled by the emit, so probably this concern would be better targeted towards the [emitters](https://github.com/guacsec/guac/tree/cf8ab736b5f895af4e86a570fd9d29a6a51dc15a/pkg/emitter), as they handle the interaction with external systems

The consumers of this package need not use the emitters as it is not an internal API.

**Comment by lumjjb** [comment]
I think the understanding of channels by the general systems programmer is such that it shouldn't be a big concern. I don't think its worth the tradeoff.
