### ISSUE TITLE
Create GraphQL documentation after APIs are fully included

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#401]
With the new refactor for graphQL and new ontology (#218 #223), there new graphQL interfaces being implemented - such as #398 #399 #391 #394 #396 #397. 

Once the graphQL API has been included, it would be helpful to have additional documentation to explain the nuance of the interfaces and APIs.

**Comment by pxp928** [comment]
@mihaimaruseac We can close this issue based on the documentation?

**Comment by mihaimaruseac** [comment]
Yes, this can be closed
