### ISSUE TITLE
Exported function with unexported type in oci.go

### ISSUE THREAD

**Issue by naveensrinivasan** [guacsec/guac#407]
This type isn't exported `*ociCollector` but the func is exported 
https://github.com/guacsec/guac/blob/cf8ab736b5f895af4e86a570fd9d29a6a51dc15a/pkg/handler/collector/oci/oci.go#L46

**Comment by lumjjb** [comment]
yes , this is standard golang semantics and is intentional, this prevents anything outside the package from initializing the struct on their own. There is nothing wrong with doing this. Can you do us a favor and help to close out these issues and PRs related to this issue.

**Comment by lumjjb** [comment]
In the future, please open 1 issue for the type of issue and not one for each individual instance, it makes triage way more difficult.

**Comment by naveensrinivasan** [comment]
Closed the PR and issue.

**Comment by naveensrinivasan** [comment]
Let me know 

> In the future, please open 1 issue for the type of issue and not one for each individual instance, it makes triage way more difficult.

I was under the intention to keep things separate so that each one of these can be addressed separately.
