### ISSUE TITLE
Logging library not being developed anymore

### ISSUE THREAD

**Issue by rgreinho** [guacsec/guac#41]
For logging, the [logrus](https://github.com/Sirupsen/logrus) library is being used. However is it not actively developed anymore:

> Logrus is in maintenance-mode. We will not be introducing new features. It's simply too hard to do in a way that won't break many people's projects, which is the last thing you want from your Logging library (again...).

They recommend using other libraries:

> Check out, for example, [Zerolog], [Zap], and [Apex].

[zerolog]: https://github.com/rs/zerolog
[zap]: https://github.com/uber-go/zap
[apex]: https://github.com/apex/log

**Comment by lumjjb** [comment]
i like zap!
