### ISSUE TITLE
Logging not working in collectsub server

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#450]
The context isn't actually being passed from the `Serve` function and thus the logging introduced in https://github.com/guacsec/guac/pull/436 doesn't actually work. This needs to be fixed so logging works.

**Comment by lumjjb** [comment]
fyi @naveensrinivasan

**Comment by naveensrinivasan** [comment]
Hi @lumjjb,
I can take care of this.

**Comment by lumjjb** [comment]
sure! Currently besides the listening log message, no other log messages are showing from calls to add or get.

The logger is part of the context in the call to https://github.com/guacsec/guac/pull/436/files#diff-8cd3be88c878305f70caa298925983e2d710c45da9184a9a6e6f47ef6312c842R79

The server is initialized and run within the following lines:
- https://github.com/guacsec/guac/pull/436/files#diff-8cd3be88c878305f70caa298925983e2d710c45da9184a9a6e6f47ef6312c842R85
- https://github.com/guacsec/guac/pull/436/files#diff-8cd3be88c878305f70caa298925983e2d710c45da9184a9a6e6f47ef6312c842R88


The server is runs the following functions with a context, but it is not the same one as passed in to the `Serve` function. Thus, some type of plumbing has to be done to ensure that the context provided to it is the one from initialized by the command running the server
- https://github.com/guacsec/guac/pull/436/files#diff-8cd3be88c878305f70caa298925983e2d710c45da9184a9a6e6f47ef6312c842R50
- https://github.com/guacsec/guac/pull/436/files#diff-8cd3be88c878305f70caa298925983e2d710c45da9184a9a6e6f47ef6312c842R64

**Comment by arorasoham9** [comment]
I can take this

**Comment by arorasoham9** [comment]
How can I test the logging once I put in my fix?

**Comment by pxp928** [comment]
> How can I test the logging once I put in my fix?

@arorasoham9 Once you have the fix in, you can run:

1. `go run ./cmd/guacgql --gql-debug` to bring up the in-mem database with graphql
2. `go run ./cmd/guaccsub` - this is the collectsub server (this is what you are checking to see that logs display properly)
3. `go run ./cmd/guacone collect files ../guac-data/docs/spdx/spdx_vuln.json` will communicate to the  collectsub server

**Comment by arorasoham9** [comment]
Since the context needs to be the same for every server being created I was thinking I will just add a `context.Context` type field to the server struct, and initialize it in `cmd/guacsub/cmd/root.go` rootCmd function and remove the  context parameter in all three functions in `pkg/collectsub/server/server.go`.

**Comment by arorasoham9** [comment]
Since this fix requires the context field to exist in the server struct and all packages are imported from GitHub should I create a PR with the field addition first?

**Comment by pxp928** [comment]
Copied from the comments I made on #995 (adding it here so it does not get lost):

There are multiple ways to do this but probably the easiest is to store the logger in the server struct:
```
type server struct {
	pb.UnimplementedColectSubscriberServiceServer

	// Db points to the backend DB, public for mocking testing purposes.
	Db   db.CollectSubscriberDb

	logger *zap.SugaredLogger
	port int
}
``` 

and inialized in `Serve`:

```
func (s *server) Serve(ctx context.Context) error {
	logger := logging.FromContext(ctx)
	s.logger = logger
	....
```

This will allow access to `AddCollectEntries` and `GetCollectEntries` to use the logger from the server struct `logger := s.logger`. Adding another context will result in confusion about which context is being used.

**Comment by pxp928** [comment]
@arorasoham9 Apologies but there is a better way to do this. See this article: https://medium.com/hootsuite-engineering/golang-grpc-distributed-context-propagation-5809e2d66db4 under the section "Context Propagation is just the start of the journey". This shows the way to propagate this logger through the ctx. This way, we don't have to pass the logger around.
