### ISSUE TITLE
Design CloudEvent based pub-sub architecture

### ISSUE THREAD

**Issue by dejanb** [guacsec/guac#460]
CloudEvents specification (https://cloudevents.io/) provides a way to define events sent between collectors and processors in a standard way. Furthermore, it is then possible to exchange these events over different protocols (nats, kafka, http, grpc, ...) and use different languages (go, rust, ...) for sending/receiving events. 

Using CloudEvents would make Guac architecture more open and easier to integrate with.

This is just a placeholder for the long-term planning and further discussions.

**Comment by pxp928** [comment]
Hey @dejanb! Looking forward to chatting about this more. Would be a great addition.

**Comment by pdxjohnny** [comment]
Hi all, we're looking at ActivityStreams/Pub based pub-sub over here: https://codeberg.org/forgejo-contrib/discussions/issues/12

**Comment by pxp928** [comment]
cloud events being created for ingestion events. See PR #1664
