### ISSUE TITLE
Add Kubernetes deployment

### ISSUE THREAD

**Issue by dejanb** [guacsec/guac#461]
Implement Helm charts for easy deployment of Guac on Kubernetes platforms.

**Comment by lumjjb** [comment]
I believe @sunnyyip is starting on this!

**Comment by trmiller** [comment]
confirmed!  We are actively working on this.

**Comment by pxp928** [comment]
@sunnyyip Can you update this issue with the work and link to the new helm charts? We can also this issue if that is all done.

**Comment by sunnyyip** [comment]
GUAC Helm Chart is available at https://github.com/kusaridev/helm-charts/tree/main/charts/guac
