### ISSUE TITLE
Add make command to check if necessary build/test tools are installed

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#472]
Currently the makefile uses a suite of tools such as `olangci-lint`, `protoc`, `docker`, etc. 

We should have something in the makefile that checks if these tools are installed and should provide the right error messages if they are not. This can be one to check for all like `make check-tools`, but also individual checks for specific commands - like building a container with `make container` will call `make container-tool-check` will check for the docker command only if someone decides to use it.

**Comment by naveensrinivasan** [comment]
I can work on this

**Comment by lumjjb** [comment]
awesome! Thanks @naveensrinivasan , assigned to you!
