### ISSUE TITLE
Figure out the roles of different binaries and their flags

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#531]
Right now, we have quite a [few different binaries](https://github.com/guacsec/guac/tree/main/cmd/), but at the same time with a lot of overlap and duplication both of functionality (with slight variations for debugging or for legacy reasons, and flags which are used partially by only some commands - although their configuration is global). 

For example, with graphQL server, what's required is the port, and the backend. However for the client only needs the endpoint path (http://guac-graphql:8080/query). Is the philosophy that the same configuration file be used for all commands within a binary - and maybe across binaries? 

Other considerations also include when we have multiple servers we need to run, how would we want to encode that configuration.

**Comment by pxp928** [comment]
@lumjjb this should be complete with https://github.com/guacsec/guac/issues/809?

**Comment by mihaimaruseac** [comment]
I think so too

**Comment by lumjjb** [comment]
Agreed - closing
