### ISSUE TITLE
Update Certifier to use GraphQL interface rather than cypher

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#571]
We've updated the assembler to be interfaced via GraphQL. Cypher should no longer be the way in which the metadata is queried. Certifiers use [component queriers](https://github.com/guacsec/guac/tree/main/pkg/certifier/components), which currently use Cypher to query components it is looking for. It should be updated with calls to the [graphql API](https://github.com/guacsec/guac/tree/main/pkg/assembler/graphql/schema) instead.

**Comment by mihaimaruseac** [comment]
First step is to define the query in clients/operations, then autogenerate the Go binding, then replace with a call to that, similar to how we do ingestion

**Comment by pxp928** [comment]
completed with https://github.com/guacsec/guac/pull/634
