### ISSUE TITLE
Scorecard runner unable to use sha due to prefix in digest

### ISSUE THREAD

**Issue by nathannaveen** [guacsec/guac#573]
## Description:
The current implementation of the scorecard runner in the scorecard.go file takes a digest with a "sha1:" prefix at the beginning. However, this prefix causes the scorecard runner not to be able to use the sha.

I have identified the issue and proposed a code fix for it. The fix involves removing the `"sha1:"` prefix from the digest before passing it to the scorecard runner.

## Solution:

Here's the proposed code fix:

``` go
digest := strings.TrimPrefix(digest, "sha1:")
```

I have tested this, and it will allow the scorecard runner to properly run.

**Comment by pxp928** [comment]
hey @nathannaveen you will not need to do this once we update to the new architecture where the digest and algorithm will be separated:

```
type Artifact struct {
    Algorithm string `json:"algorithm"`
    Digest    string `json:"digest"`
}
```

**Comment by nathannaveen** [comment]
Ok, Thanks! I will close this issue once the new code is in place.

**Comment by pxp928** [comment]
I was mistaken. We are not using an artifact node. It will be part of the source node. We will need this fix. I will incorporate this in :)

**Comment by pxp928** [comment]
Completed with https://github.com/guacsec/guac/pull/631 and https://github.com/guacsec/guac/pull/634
