### ISSUE TITLE
Add ability to parse identifier strings for  Github Release URLs

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#591]
With the inclusion of PURL and GitHubRelease additions to collectsub/datasources(#589), we now have the ability to create collect subscription requests for PURLs. [Identifier strings](https://github.com/guacsec/guac/blob/main/pkg/collectsub/collectsub/input/identifier_strings.go) struct should be expanded to include Github Release URLs and guessers should be implemented for unclassified strings to find potential Github Release URLs.

**Comment by riybha216** [comment]
Can @maddieBruk and I work on this issue?

**Comment by pxp928** [comment]
Sure! Let us know if we can clarify anything or if you have questions.

**Comment by maddieBruk** [comment]
Will do! thanks!

**Comment by stevemenezes** [comment]
Is anyone still working on this issue?

**Comment by pxp928** [comment]
@riybha216 and @maddieBruk are you working on this issue?
