### ISSUE TITLE
[memory backend] Add IDs and back edges

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#597]
Breakout of current work on the in-memory backend to add IDs and back edges:

| Types                 | AssignedTo   |
|-----------------------|--------------|
| `artifact`            | @jeffmendoza |
| `builder`             | @jeffmendoza |
| `certifyBad`          |   @pxp928           |
| `CertifyScorecard`    |  @pxp928             |
| `CertifyPackage`    |  @jeffmendoza             |
| `CertifyVexStatement` |  @pxp928             |
| `CertifyVuln`         |   @pxp928           |
| `CVE`                 | @pxp928      |
| `GHSA`                | @pxp928      |
| `hasSBOM`             |  @jeffmendoza            |
| `hasSLSA`             | @jeffmendoza |
| `hasSouceAt`          | @mihaimaruseac  / @pxp928      |
| `hashEqual`           | @jeffmendoza |
| `isDependency`        | @pxp928             |
| `isOccurrence`        | @jeffmendoza |
| `isVulnerability`     | @pxp928             |
| `osv`                 | @pxp928      |
| `package`             | @mihaimaruseac / @pxp928      |
| `source`              | @mihaimaruseac  / @pxp928     |

**Comment by jeffmendoza** [comment]
I'll start on `builder` and `hasSLSA` now

**Comment by jeffmendoza** [comment]
I think we can close this now.
