### ISSUE TITLE
Implement support for ingesting artifacts from CycloneDX SBOM files

### ISSUE THREAD

**Issue by dejanb** [guacsec/guac#632]
#584 implemented support for ingesting packages and dependency relations from cdx files. We still need to properly ingest artifacts (based on hashes) and tied them to packages using `isOccurence` relations where appropriate,

**Comment by pxp928** [comment]
@dejanb are you working on this? Let me know if you need some help to finish this up.

**Comment by dejanb** [comment]
@pxp928 I'll be able to get back to this in a few days. Feel free to jump on it in the meantime if you are up for it.

**Comment by pxp928** [comment]
Sure I can pick this up.
