### ISSUE TITLE
Behavior of Neighbors() on various backend nodes

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#653]
I went through and took a look at what we are doing

| Type             | Root/parent Node              | Neighbors                                                   |
|------------------|-------------------------------|-------------------------------------------------------------|
| ghsa             | no | certVuln, equalVuln, Vex                              |
| cve              | no                  | certVuln, equalVuln, Vex                        |
| osv              | no | certVuln, equalVuln, Vex                              |
| builder          | no                            | hasSLSA links                                               |
| artifact         | no                            | all links                                                   |
| pkgVersion       | pkgName                       | parent(pkgName), all other links                            |
| pkgName          | pkgNamespace                  | parent(pkgNamespace), all version children, all other links |
| pkgNamespace     | pkgType                       | parent(pkgType), all name children                          |
| pkgType          | no                            | all namespace children in this type                         |
| srcName          | srcNamespace                  | parent(srcNamespace), all other links                       |
| srcNamespace     | srcType                       | parent(srcType), all srcName children                       |
| srcType          | no                            | all srcNamespace children                                   |
| **links**         |                             |                                                     |
| certifyVex       | no                            | pkg/art, osv/cve/ghsa                                       |
| certifyVuln      | no                            | pkg, osv/cve/ghsa                                           |
| hasSLSA          | no                            | artifacts, builder                                          |
| hasSourceAt      | no                            | pkg, source                                                 |
| hashEqual        | no                            | artifacts                                                   |
| isDep            | no                            | pkg, depPkg                                                 |
| isOccurrence     | no                            | pkg/source, artifact                                        |
| isVuln           | no                            | osv, cve/ghsa                                               |
| pkgEqual         | no                            | packages                                                    |
| **leaves**         |                             |                                                     |
| certifyBad       | no                            | pkg/src/art                                                 |
| certifyGood      | no                            | pkg/src/art                                                 |
| certifyScorecard | no                            | source                                                      |
| hasSBOM          | no                            | pkg/src                                                     |

Some discrepancies:

* Package and Source have "type" nodes that will form a path between all nodes of that type. The other "nouns" don't have any root connection.

Two unrelated python packages could have a shortest path like so:

```
pkgName -> pkgNamespace -> pkgType[pip] -> pkgNamespace -> pkgName
```

A search might miss a longer dependency chain that links these two.

Current recommendation to find this path would be to do a client-side search and filter the direction that package links are followed.

**Comment by mihaimaruseac** [comment]
Neighbors should include anything that is linked and has an id.

**Comment by jeffmendoza** [comment]
decision from discussion:

Remove cveYear, ghsaRoot, and osvRoot. (Or maybe just remove from Neighbors())

This will prevent this case:

```
pkgVersion -> certifyVuln -> osv -> osvRoot -> osv -> certifyVuln -> pkgVersion
```

Packages and sources will still be linked by top-level `Type`. Client-side filtering will be used if we don't want to search Namespace or Type for packages and sources.

**Comment by pxp928** [comment]
@jeffmendoza can we close this issue?
