### ISSUE TITLE
Update Path Example in GraphQL demo

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#699]
The [path example](https://github.com/guacsec/guac/blob/main/demo/GraphQL.md#finding-paths) used to follow a route through dependencies in a container image, now it returns a path through the golang type node. Find a different example or update the text.

**Comment by mihaimaruseac** [comment]
Let's add node filters to force it to go in the direction we want?

**Comment by jeffmendoza** [comment]
Yes, sounds good. We could run as is and then have a second example with a filter.
