### ISSUE TITLE
SPDX parser top level heuristic change to check "DESCRIBES" relationship

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#708]
The SPDX top level purl construction for `guac:spdx/...` is a heuristic for documents that don't properly include DESCRIBES relationships to talk about what package they are describing. We should add some logic in the SPDX parser to not define this top level package otherwise and just walk the tree from the packages that the document describes.

https://github.com/guacsec/guac/pull/707/files/78907de874199482af3549719a1e25f2735db0b9#r1162839713

**Comment by CrossedSecurity** [comment]
working on this now
