### ISSUE TITLE
Add missing unit test for memory backend

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#716]
Need to add unit tests for each nodes in the [in-memory backend](https://github.com/guacsec/guac/tree/main/pkg/assembler/backends/inmem) 

| Types                 | AssignedTo   |
|-----------------------|--------------|
| `artifact`            | @pxp928|
| `builder`             |@pxp928 |
| `certifyBad`          |    @jeffmendoza         |
| `certifyGood`          |     @jeffmendoza        |
| `CertifyScorecard`    |   @jeffmendoza           |
| `CertifyVexStatement` |   @jeffmendoza           |
| `CertifyVuln`         |  @jeffmendoza           |
| `CVE`                 |   @jeffmendoza   |
| `GHSA`                |  @jeffmendoza    |
| `hasSBOM`             |    @jeffmendoza   |
| `hasSLSA`             |@jeffmendoza |
| `hasSouceAt`          |   @jeffmendoza     |
| `hashEqual`           | @jeffmendoza |
| `isDependency`        |     @jeffmendoza        |
| `isOccurrence`        | @jeffmendoza |
| `isVulnerability`     |  @jeffmendoza           |
| `osv`                 |   @jeffmendoza   |
| `path`                 |   @jeffmendoza   |
| `package`             |   @pxp928   |
| `pkgEqual`    |      @jeffmendoza        |
| `source`              |   @jeffmendoza  |

**Comment by pxp928** [comment]
Please assign yourself or comment on which ones you are going to tackle.

**Comment by jeffmendoza** [comment]
I'll do csv/osv/ghsa next

**Comment by jeffmendoza** [comment]
I'll to isvuln, certify vuln, certifyvex next.

**Comment by jeffmendoza** [comment]
Next for me: certify{good/bad/scorecard}
