### ISSUE TITLE
[Ontology] Have isDependency include information on direct or indirect or unknown

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#748]
It is helpful in patch planning to know if the dependencies are direct or indirect. So as to know if the informatino gathered was flattened or not. Certain SBOMs do this and some don't and we want to encourage this information to be exposed as well as structure helps in patch planning.

https://github.com/google/deps.dev/issues/12

**Comment by pxp928** [comment]
Updated `isDependency` schema to include  direct/indirect/unknown enum
