### ISSUE TITLE
Add license information into `hasSourceAt`

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#755]
Currently, we are not capturing license information for the various projects. This information is available to be captured from deps.dev. The schema for `hasSourceAt` would need to be updated to add this field.

**Comment by jeffmendoza** [comment]
Licenses regularly change on projects and should be attached to package version

**Comment by pxp928** [comment]
`HasSourceAt` can be linked to the package version so it can still belong there linking it to the specific version of the package it represents

**Comment by jeffmendoza** [comment]
Also, it could be a matter of opinion, different scanners produce different results, so It should be something that is attached with a "justification" and lists the scanner/tool that determined the version.

**Comment by pxp928** [comment]
`HasSourceAt` does have a collector and origin, so that can be used to determine where this information came from (ie deps.dev)

**Comment by pxp928** [comment]
closing this as https://github.com/guacsec/guac/issues/1014 covers how to effectively capture licenses in GUAC.
