### ISSUE TITLE
Fix processor and parser PUBSUB tests to check for logger err msgs

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#765]
Initially, we returned errors from the processor/parser through the PUBSUB flow. However, this causes the `guacone` ingestor to stall (https://github.com/guacsec/guac/issues/763) unintentionally. The fix is to not return an error when processing a doc happens (https://github.com/guacsec/guac/pull/764)...

However, this makes the tests fail as it no longer returns for an error to check for. This should be changed so that a test logger can be passed in context to see if an error has occurred.

See https://github.com/guacsec/guac/pull/764/files for commented out tests to fix

**Comment by stevemenezes** [comment]
Do we want to implement something like this for our tests https://github.com/sirupsen/logrus/blob/master/hooks/test/test_test.go#L16? Just curious.

**Comment by lumjjb** [comment]
ooo that would be really neat!

**Comment by stevemenezes** [comment]
@lumjjb do we still want to keep the [[processor: uuid]](https://github.com/guacsec/guac/pull/764/files#diff-63225ec852ad23c5e51f51a987209adf4f2511eb4f4bef373075abef2c256542R86) part of the logs? Might be a hinderance to assert the logged string since uuid gets generated within the method.

**Comment by stevemenezes** [comment]
Upon discussion with @lumjjb seems like in the long term, it would be preferred to have a separate function for the test logger that would be forced to run by setting some flags. Scrapping the idea of using logrus or something similar for now.

**Comment by arorasoham9** [comment]
I can take this one.

**Comment by arorasoham9** [comment]
@lumjjb @stevemenezes As a fix for this issue, I am trying to insert a zap logger into the ctx, and retrieve it in Subscribe function. When the subscribe function returns in the testing function, I check if the log messages contain any common keyword between all the error messages. Please let me know if this sounds like a good fix. Thanks!
