### ISSUE TITLE
Update IsDependency to show direct/indirect and toolchain to utilize that

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#769]
In light of the discussion in https://github.com/google/deps.dev/issues/12, it looks like we are able to parse the entire structure of the transitive depedencies from one deps.dev call. At the same time, it looks like it is useful to update our toolchain to encode the information available there (direct dependencies through the returned edges), as well as handling version ranges properly... 

These are the set of things that need to be worked on

- ~[GraphQL] Add direct/indirect/unknown enum for IsDependency~
- ~[Ingestion/Parsers] Update parsers for IsDependency to include direct/indirect/unknown info~
- ~[Deps.dev collector] Update parsing for [deps.dev](http://deps.dev/) to include structure of the tree~
- [guac-visualizer] Update to read version ranged properly (for  badcertify demo)
- ~[guacone queryvuln] Update guacone to read version ranged properly (for query_vuln demo)~
- ~[Deps.dev collector] (optional) enable Collectsub identifier strings~

**Comment by pxp928** [comment]
Completed Items via #778:
- Added direct/indirect/unknown enum for IsDependency
- [Deps.dev Parser] Updated parser for IsDependency to include direct/indirect/unknown info
- [Deps.dev collector] Updated parsing for [deps.dev](http://deps.dev/) to include structure of the tree
- [Deps.dev collector] enabled Collectsub identifier strings

Remaining Items:
- Update the SPDX and CDX parsers to properly use direct/indirect/unknown info in IsDependency
- [guac-visualizer] Update to read version ranged properly (for badcertify demo)
- [guacone queryvuln] Update guacone to read version ranged properly (for query_vuln demo)

**Comment by pxp928** [comment]
Here are the various outputs that can be received for the version range from [deps.dev](http://deps.dev/) for the various "systems":
```
curl -s https://api.deps.dev/v3alpha/systems/npm/packages/react/versions/17.0.0:dependencies | jq
curl -s https://api.deps.dev/v3alpha/systems/cargo/packages/bincode/versions/1.3.3:dependencies | jq
curl -s https://api.deps.dev/v3alpha/systems/maven/packages/com.cloudhopper:ch-mq/versions/3.0.3:dependencies | jq
curl -s https://api.deps.dev/v3alpha/systems/pypi/packages/pytest/versions/7.3.1:dependencies | jq
curl -s https://api.deps.dev/v3alpha/systems/go/packages/cloud.google.com%2Fgo/versions/v0.102.1:dependencies | jq
```

**Comment by lumjjb** [comment]
We have revamped the UI to not handle this logic, so this issue should be complete
