### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#791]
RE: https://github.com/guacsec/guac/pull/779#discussion_r1176858639

We should document the steps we will take to generate a release. Ex: Create a tag, check the build, make a release in GitHub, etc.

**Comment by mihaimaruseac** [comment]
Maybe we can make it all an automated workflow using GitHub Actions?

**Comment by lumjjb** [comment]
it looks like this is all codified now in the CI, @jeffmendoza does this issue change to just having something in the readme to point to the github workflow?
