### ISSUE TITLE
[ingestion bug] Failure due to missing purl attribute

### ISSUE THREAD

**Issue by stevemenezes** [guacsec/guac#828]
**Describe the bug**

We tried to ingest sbom files (both CDX and SPDX) using the latest guacone binary (on the main branch) however it errors out for a few files. Following are the logs for the same.

 `"msg":"emit error: unable to assemble graphs: Node {<image-name>[sha256:95a7593269fc3344af31c8825e72da6f705dd753417581dd0391e0296ed81242] sha256:95a7593269fc3344af31c8825e72da6f705dd753417581dd0391e0296ed81242 [] [container] {file:///<file-absolute-path>.cdx.json FileCollector}} has no value for property purl","stacktrace":"github.com/guacsec/guac/pkg/handler/collector.Collect\n\t/Users/smenezes/dev/guac-exp/guac/pkg/handler/collector/collector.go:100\ngithub.com/guacsec/guac/cmd/guacone/cmd.glob..func5\n\t/Users/smenezes/dev/guac-exp/guac/cmd/guacone/cmd/files.go:169\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/smenezes/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/smenezes/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/smenezes/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\ngithub.com/guacsec/guac/cmd/guacone/cmd.Execute\n\t/Users/smenezes/dev/guac-exp/guac/cmd/guacone/cmd/root.go:104\nmain.main\n\t/Users/smenezes/dev/guac-exp/guac/cmd/guacone/main.go:23\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}`

**To Reproduce**

**Expected behavior**

**Screenshots**

**GUAC version**
Are you using a released version of GUAC or one build from a commit in the
repository?
The one on the main branch.

**Additional context**

**Comment by pxp928** [comment]
Hey @stevemenezes, this looks like an old bug (and an error message). If you are on a fork, are you working from the latest commit on the main branch?

**Comment by stevemenezes** [comment]
Hey @pxp928 thanks for getting back to me. Yeah I just tried with the latest commit on the main branch too however, I'm seeing similar error messages.
`emit error: unable to ingest doc tree: unable to parse purl pkg:guac/cdx/@sha256:431168b67a3f620e2cda29cdf38af300c546fa8fd7e10192905bb3ef89c36f5f?tag=latest: name is required`

Also seeing `unable to create entries in collectsub server, but continuing: unable to add collect entries: rpc error: code = Unavailable desc = connection error` but I think nodes are being injected as seen in the graphQL playground. Is that expected? Any insights would be helpful thanks!

**Comment by pxp928** [comment]
Would you be able to share the CDX SBOMs [top-level component name](https://cyclonedx.org/docs/1.4/json/#metadata_component_name)? Looks like it might be an issue with how we parse the name to create the purl. 

Also, `unable to create entries in collectsub server, but continuing: unable to add collect entries: rpc error: code = Unavailable desc = connection error` is not an issue. This is for the collector subscriber server that runs to provide more insights via deps.dev and others. This is not needed for the ingestion to be successful (so that error can be ignored for now).

**Comment by stevemenezes** [comment]
sure! The component name has the following format - `foo.registry.com:4443/myapp/debian:latest`

**Comment by pxp928** [comment]
@stevemenezes This PR -> https://github.com/guacsec/guac/pull/830 should fix your issue. Please give it a try and let me know. Thanks!

**Comment by stevemenezes** [comment]
Just tried it worked fine except for one of the files. Now seeing this error - `unable to ingest doc tree: unable to parse purl : scheme is missing`

**Comment by lumjjb** [comment]
Hi, would you be able to share the top level component metadata / name of
that file? Thanks

**Comment by pxp928** [comment]
@stevemenezes I updated the PR with some changes to might fix this error `unable to ingest doc tree: unable to parse purl : scheme is missing`. Let me know if it does. If not, would you be able to share the generated SBOM for our testing?

**Comment by stevemenezes** [comment]
Just tried the new changes, rebuilt the binary and I see no errors, seems like it worked!

**Comment by pxp928** [comment]
Thanks @stevemenezes! Can you share your usecase and what you are doing/ planning to do with GUaC? Let us know if there are any features you would like to see.

**Comment by stevemenezes** [comment]
For now we're playing around with our sboms to see if GUAC allows us to ingest and query the required data correctly. One thing I also noticed is that the component properties in cdx are not being ingested at all. Also the license information is missing for both spdx and cdx data. Any insights on when that would be made available would be helpful, thanks!

**Comment by pxp928** [comment]
Yes, that is correct, we are currently not collecting all the component properties in CDX, but the license information is one of the upcoming features we will be ingesting. This is already part of the upcoming roadmap for new features we will be adding. Are their particular component properties you would like to see collected from CDX?

**Comment by pxp928** [comment]
Timeline-wise, it should be fairly straightforward and should be added a few weeks after the beta release (which is scheduled in a week or so)

**Comment by stevemenezes** [comment]
Ideally we would want to get all of the data ingested but for now we're mostly interested in `syft:package:language`, `syft:location:0:layerID`, `syft:package:type`. Will also check with the team and keep you posted.

**Comment by stevemenezes** [comment]
Hey @pxp928 yes we're putting together a doc listing the gaps we've encountered and would like to discuss with you about the same. Will keep you posted once it's ready thanks!
