### ISSUE TITLE
[question] How to ingest data in neo4j?

### ISSUE THREAD

**Issue by genos1998** [guacsec/guac#849]
## Question

I'm currently facing difficulties ingesting data into Neo4j using the latest version of Guac. However, I have successfully been able to ingest and retrieve data in the GraphQL database. I'm interested in exploring and configuring Neo4j as well. Is there something I might be overlooking? For the Neo4j configuration, I have enabled Neo4j in the Helm chart and can access the Neo4j browser by port forwarding.

and also I noticed that certifier is not a cmd any more it works automatically.. Am I right?

**Comment by pxp928** [comment]
Hello @genos1998, the latest version of GUAC does not currently support a fully functional neo4j. We are working towards adding support for a persistent database based on community feedback. More information on the community meetings (happening this week on Thursday) can be found [here](https://github.com/guacsec/guac#communication). Based on feedback, our first priority will be adding a persistent database. 

As for the certifier, utilizing the docker-compose or helm chart, they do run automatically. They can also be run manually using `./bin/guacone certifier <certifier (osv or scorecard)>`.

**Comment by genos1998** [comment]
I understand, @pxp928. I have one final question. When I was using the previous version of Guac (v0.0.1), I observed that running the certifier command multiple times resulted in the creation of duplicate attestation nodes. I'm wondering if these nodes are truly duplicates or if there's something that I might have missed.

**Comment by pxp928** [comment]
As the GUAC nodes in the database are immutable, new nodes are created if/when information changes. For example, in the new version, we add a timestamp to the osv certifier to when it was last scanned. This allows the certifier to re-run again create a new node based on the updated information it receives from OSV. We are working on integrating a garbage collection at a later date to clean out old unneeded nodes.

The older v0.0.1 was not as robust as the current version on main. In the current version, the user can specify when they want to re-check OSV (or another vulnerability database) for updated vulnerability information on a particular package and create a new "certifyVulnerability" node. So they could be duplicates (with no new information) but the timestamp will be different on the node to indicate that it was scanned and the vulnerability information remained the same. This way the certifier knows what it needs to recheck (based on the timestamp) and skip the ones that already have updated information.

**Comment by genos1998** [comment]
Than so much for the quick replies @pxp928
