### ISSUE TITLE
[feature] Which DB backend do we want to see?

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#851]
Discussions @ https://docs.google.com/document/d/1wk7N9zggygz1Xx7qgx1aEt3niPpAEkRpdQi5i7k0Cj8/edit#

With the new GraphQL interface, we are able to implement multiple database as GUAC's GraphQL backend.

Right now we've implemented an in-memory database, and its tests, which will act as a conformance suite to the GraphQL backend. This puts us in a position to now have multiple DB implementations to the GraphQL interface.

Considerations of implementation of the backend will include:
- The ask from community members that are looking to run GUAC (prioritizing production use cases)
- The number of contributors who are interesting in implementing the use case
- The license of the DB libraries 
- Usage factors / considerations / trade-offs
  - speed
  - scale
  - ease of use

Note that the backends may be any type of database, from graph DBs (ArrangoDB / Neo4j) to more "traditional" DBs (Postgres, Spanner), or even a file system!

**We'd like to get community input on what Databases they'd like to see in GUAC, with additional information about their use case and scale if available!**

**Comment by anoop2811** [comment]
I think if a traditional database could Postgres is available, that would be great if we dont lose any capability with GUAC for using it instead of a graphdb. The reason is mostly already talent available within the company and ease of using a cloud vendor that supports it.

**Comment by sjbodzo** [comment]
There are projects built on Postgres to expose it as a Graphql layer, and they can take you pretty far. Id also recommend looking at [surreal db](https://surrealdb.com). It has lots of interesting features, including the ability to run embedded or standalone.

**Comment by mihaimaruseac** [comment]
I just looked at the [Go package](https://pkg.go.dev/github.com/surrealdb/surrealdb) for surreal and it's at an old version. Probably this can be fixed with a non-beta release on surreal.

Though, there's also a potential issue that surreal's license is not yet fully Open Source, so it is unclear if we will be able to use it.

**Comment by mihaimaruseac** [comment]
I've tested ArangoDB and several other databases and the result is that ArangoDB is significantly faster. Full post at https://mihai.page/testing-graph-databases/

**Comment by jens1o** [comment]
It'd be great if we could use CloudSQL, also.

**Comment by jens1o** [comment]
> > It'd be great if we could use CloudSQL, also.
> 
> We do have support for [ENT](https://github.com/ent/ent). That should be able to support CloudSQL (for databases that can be managed by CloudSQL)

Ah nice to know, thanks @pxp928 ! I'm looking into that.

**Comment by lumjjb** [comment]
We discussed this during the recent community meeting. We have decided to put efforts behind Ent and the inmem/keyvalue backend in the time being until we hit a stable interface (i.e. 1.0)
