### ISSUE TITLE
[fix] issue with scorecard runner timing out  

### ISSUE THREAD

**Issue by pxp928** [guacsec/guac#868]
**Is your feature request related to a problem? Please describe.**

Move [scorecard runner unit test](https://github.com/guacsec/guac/blob/main/pkg/certifier/scorecard/scorecardRunner_test.go) to run post merge as multiple hits to GitHub API causes a [timeout](https://github.com/guacsec/guac/actions/runs/5018856763/jobs/8998731791?pr=866#step:7:158).

**Describe the solution you'd like**
~~Change such that the scorecard runner runs only on post merge.~~

EDIT: To give more clear solution

Change such that the scorecard runner tests only run when the PR is approved and merged to main (post-merge). Changing the `//go:build integration` to a different tag, then run this test in a separate workflow.

**Comment by pxp928** [comment]
With the merger of  https://github.com/guacsec/guac/pull/906, this can be added to that existing workflow.

**Comment by arorasoham9** [comment]
@pxp928 Please correct me if I am wrong, but the only requirement now is to change the build tag in [scorecard runner unit test](https://github.com/guacsec/guac/blob/main/pkg/certifier/scorecard/scorecardRunner_test.go)

**Comment by pxp928** [comment]
yes, that is correct!

**Comment by pxp928** [comment]
completed with https://github.com/guacsec/guac/pull/927
