### ISSUE TITLE
Slow ingestion due to chatty GraphQL

### ISSUE THREAD

**Issue by mihaimaruseac** [guacsec/guac#883]
Ingesting documents with large number of components can be slow, especially if the database server is remote (or via Kubernetes, etc.). This is because the GraphQL communication is chatty. For example, if an SBOM has 200 dependencies, we have 200 `IngestDependency` roundtrips.

We can (and should) batch these, but this could result in larger documents. We should profile and find the nice sweet spot where we batch up to N requests.

**Comment by lumjjb** [comment]
This issue has been resolved by batch ingestions (e.g. https://github.com/guacsec/guac/pull/999)
