### ISSUE TITLE
build arm64 arch image

### ISSUE THREAD

**Issue by sunnyyip** [guacsec/guac#887]
The current ghcr.io/guacsec/guac image is built for amd64 arch. We should build one to support for arm64 arch which will make testing on that platform, e.g. mac, more performant.

e.g.
The same operation for ingesting a file can take up to 70% more time to complete when using an amd64 image on arm64 machine. 
{"level":"info","ts":1684855007.227823,"caller":"cmd/files.go:167","msg":"[10.149113339s] completed doc {Collector:FileCollector Source:file:////data/docs/spdx/spdx_vuln.json}"}

{"level":"info","ts":1684853976.1924722,"caller":"cmd/files.go:167","msg":"[17.306136507s] completed doc {Collector:FileCollector Source:file:////data/docs/spdx/spdx_vuln.json}"}

**Comment by tuananh** [comment]
if no one is working on it, i'll take it

**Comment by pxp928** [comment]
Assigned to you @tuananh! Thanks!

**Comment by pxp928** [comment]
related to issue #904
