### ISSUE TITLE
align the path to guac binaries between images built by makefile and github release workflow

### ISSUE THREAD

**Issue by sunnyyip** [guacsec/guac#903]
At the moment the locally built local-organic-guac image, by the Makefile, has the guac binaries at /opt/guac and the one used by the helm chart, ghcr.io/guacsec/guac, has them at /cnb/process.

We should align the location where the binaries are stored at /opt/guac so they can be referenced consistently between the two deployment approaches and configuration.

**Comment by pxp928** [comment]
Work completed in https://github.com/guacsec/guac/pull/918
