### ISSUE TITLE
docker tool check in Makefile fails when running "make container"

### ISSUE THREAD

**Issue by arorasoham9** [guacsec/guac#909]
**Describe the bug**
When going through the setup for Guac, post cloning the repositories, running "

**To Reproduce**

1. Complete step 1
2. Try building the container in step 2
3.  See below error

**Expected behavior**
Docker and all other required dependencies were installed using the guides provided under the pre-requisites section. Hence, the check should have gone through. Commenting out the check in the makefile fixes it.

**Screenshots**
![image](https://github.com/guacsec/guac/assets/68672198/3682096d-1114-4fae-91c7-842720cac31a)

**GUAC version**
Are you using a released version of GUAC or one build from a commit in the
repository?

Commit in the repository.

**Additional context**
N/A

**Comment by arorasoham9** [comment]
I get the following output
`/usr/bin/docker
`

**Comment by lumjjb** [comment]
It looks like the makefile uses the "command" cli, which maybe has a different behavior? If that's causing an issue we should move to using "which".

**Comment by pxp928** [comment]
> I get the following output `/usr/bin/docker `

@arorasoham9 Could you also run `command -v docker` to see what that outputs?

**Comment by arorasoham9** [comment]
@pxp928 `command -v  docker` also outputs `/usr/bin/docker`

**Comment by mlieberman85** [comment]
This is definitely a bit strange. I would expect

```
@if ! command -v $(CONTAINER) &> /dev/null; then \
		echo "'$(CONTAINER)' is not installed. Please install '$(CONTAINER)' and try again. Or set the CONTAINER variable to a different container runtime engine."; \
		exit 1; \
fi
```

to silence all stdout and stderr and yet `/usr/bin/docker` is showing up there. Do you know what shell and version of it you're running?
