### ISSUE TITLE
[feature] can we have snapshot daily build 

### ISSUE THREAD

**Issue by tuananh** [guacsec/guac#941]
Currently it's moving quite fast and we would love to try snapshot daily build to get the latest fixes and feats.

**Comment by pxp928** [comment]
That's a good idea @tuananh! We can start doing that if it helps the community.

**Comment by sunnyyip** [comment]
At the moment, goreleaser is run by the release workflow at https://github.com/guacsec/guac/blob/main/.github/workflows/release.yaml#L56-L78. The type of build it runs (snapshot/release) is based on the event that triggered the workflow.

I'd like to move all the goreleaser commands into the Makefile and have the release workflow consume it. Similar to how we build the local-organic-guac image for local testing - https://github.com/guacsec/guac/blob/main/Makefile#L105-L121
This would allow people to test the builds more easily and consolidate all goreleaser commands into one place.

With that, a nightly build would be a make target with specific goreleaser inputs defined for a specific github event triggers representing the nightly build - e.g. push of a 'nightly' tag - and the build should replace the nightly build artifacts (bins/container image) produced from the previous night.
