### ISSUE TITLE
[bug]  Fail to run the demo - in the Build the containers step

### ISSUE THREAD

**Issue by maorkuriel** [guacsec/guac#949]
**Describe the bug**
The Make container command fails with this error:
```
   • building docker image                          image=ghcr.io/guacsec/guac:v0.0.0-local-organic-guac-amd64
  ⨯ release failed after 24s                 error=docker build failed: failed to build ghcr.io/guacsec/guac:v0.0.0-local-organic-guac-amd64: exit status 1: ERROR: use `docker --context=default buildx` to switch to context "default"
```

**To Reproduce**
Just setup a clean environment on a MacOs with an M1 Pro chip 

![Screenshot 2023-06-19 at 13 16 18](https://github.com/guacsec/guac/assets/32849081/288d1d4d-2045-4c6f-8839-0989e77d98d1)

maorkuriel@MaorKuriel guac % go version
go version go1.20.5 darwin/arm64 
![Screenshot 2023-06-19 at 13 17 03](https://github.com/guacsec/guac/assets/32849081/4c5316a9-27a6-4881-aa03-460ea49699c2)

 
**Expected behavior**
seeing the GUAC containers

**Screenshots**
![Screenshot 2023-06-19 at 13 13 15](https://github.com/guacsec/guac/assets/32849081/9e4f3aec-6791-408e-9b16-1fc7c511f88b)

**GUAC version**
 I used the version that I got from the git command in the demo guide
`git clone https://github.com/guacsec/guac.git
`

**Comment by pxp928** [comment]
Can confirm on my M1 Mac that the above solution posted by @sunnyyip solves the issue. I added `- "--builder=desktop-linux"` to the bottom of `build_flag_templates` in https://github.com/guacsec/guac/blob/main/.goreleaser.yaml#L16 and https://github.com/guacsec/guac/blob/main/.goreleaser.yaml#L29

**Comment by maorkuriel** [comment]
Thanks, this fix worked.

**Comment by JonZeolla** [comment]
I also ran into the same issue and this fixed it for me.  M1 mac here also

**Comment by sunnyyip** [comment]
I'm prepping a PR to fix this. I will have it submitted in the next hour.
