### ISSUE TITLE
task: [ingestor]Include the github and commit id information from SLSA attestations

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#96]
SLSA level 3 attestations should contain source information, this information can be included within the graph which will help link to other data sources (e.g. scorecards)

**Comment by lumjjb** [comment]
@pxp928 this is resolved yea?

**Comment by pxp928** [comment]
No not yet. Never got a clear answer on where in the SLSA attestation this information would be stored (some tools are missing this information when generating the attestation).

**Comment by lumjjb** [comment]
Gotcha - i'm swapping the tag to long term since this would be more of a standards thing.

**Comment by pxp928** [comment]
New graphQL architecture collects this information in `builtFrom` as artifact hash. This artifact hash can be linked to a known source (which contains a tag and commit ID fields).
