### ISSUE TITLE
[ingestion/data-quality issue] Segfault in IsDependencyIngestion of SPDX docs

### ISSUE THREAD

**Issue by lumjjb** [guacsec/guac#980]
**Describe the bug**

Got a segfault while trying to ingest SPDX docs

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1641d9c]

goroutine 11347 [running]:
github.com/guacsec/guac/pkg/assembler/clients/helpers.ingestIsDependencies({0x2709220, 0xc004553440}, {0x26f6a80, 0xc0004f6f90}, {0x33010c8?, 0x14, 0x0?})
	/Users/lumb/go/src/github.com/guacsec/guac/pkg/assembler/clients/helpers/assembler.go:245 +0x17c
github.com/guacsec/guac/pkg/assembler/clients/helpers.GetParallelAssembler.func1.10()
	/Users/lumb/go/src/github.com/guacsec/guac/pkg/assembler/clients/helpers/parallel.go:147 +0x38
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/lumb/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/lumb/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5

**To Reproduce**

This was done using an arrango branch, but should not be affected by that, it was triggered through
```
 bin/guacone collect files ../guac-data/docs/spdx
```

**Expected behavior**

No segfaults :(

**Screenshots**

**GUAC version**
Are you using a released version of GUAC or one build from a commit in the
repository?

commit 53a43bad7407900ad1832366bd0e0d716c02ece0 (HEAD -> index-batch-arango, pxp928/index-batch-arango)

**Ingested document(s)**

In GUAC-data

**Additional context**
NA

**Comment by pxp928** [comment]
@lumjjb this might be fixed now?

**Comment by pxp928** [comment]
Fixed with the updates to the main branch for arango ingestion.
