### ISSUE TITLE
[feature] CDX getTopLevelPackage should check relationships before defaulting to heuristic

### ISSUE THREAD

**Issue by CrossedSecurity** [guacsec/guac#996]
Please see [here](https://github.com/guacsec/guac/pull/979/#discussion_r1246683505) for more context. The SpdxParser was updated to check packages and relationships to build top level package before defaulting to heuristic if they don't exist or are malformed. CDX should do the same.

**Comment by lumjjb** [comment]
This is fixed in https://github.com/guacsec/guac/pull/1247
